opengovsg/GoGovSG

- src/client/styles/homePage.js
When the landing image is removed, the learn more button cuts into the text above
Add padding to the bottom of the text
**BEFORE**:
**AFTER**:
> Fix layout issue when image removed

- src/client/util/QRCode.js
#7 
Currently, QR code generation is broken on Internet Explorer
As IE does not support `svg.outerHTML`, I used `XMLSerializer` instead.
As such, QR code generation and SVG download is now working, unfortunately, PNG download is still not working, this as IE forbids downloading a canvas that has been 'tainted' with an SVG inside [(source)](https://stackoverflow.com/questions/33392591/in-browser-conversion-of-svg-to-png-image-cross-browser-including-ie)
**BEFORE**:
**AFTER**:
> Fix IE qr code generation

- src/client/styles/homePage.js
- src/client/util/QRCode.js
- src/server/util/ga.ts
Closes #26.
Our previous fix to render QR code in `.png` format on FireFox required us to set a specified height and width, which has caused problems to the `.svg` side. The solution is to unset the specified height and width after rendering the `.png` format QR code.
- Committed eslint format changes.
**BEFORE**:
**AFTER**:
> Fix the SVG

- src/server/index.ts
Browsers are unnecessarily caching resources and server responses.
This results in `bundle.js` being momentarily outdated on new redeployments. IE's behaviour of caching responses without revalidation also creates problems because even after signing out, it still mistakenly thinks it is still logged in due to outdated auth-check responses.
Closes #4 and closes #5 .
Send `Cache-Control: no-store` header for every outgoing response. This is implemented using a middleware that is inserted very early in the pipeline, right before `express.static` is being used. This allows even `bundle.js` to be not be cached.
> Enforce no-cache behaviour via Cache-Control header

- .travis.yml
- Dockerrun.aws.json
- README.md
Deployments to Elastic Beanstalk were failing with an inexplicable timeout issue, preventing deployments to staging and production environments.
The initial suspect was cast on the Elastic Beanstalk version due to certain filesystem mounting warnings in `eb-activity`. However upgrading the EB platform did not resolve this issue as discovered by @yong-jie and @kylerwsm . Further investigation revealed that EB deployments have a deployment timeout that if exceeded, would terminate a deployment.
The solution was to move the image build step out of the EB deployment pipeline into the Travis pre-deploy pipeline instead. Images would be built in Travis and pushed to the AWS Elastic Container Registry before triggering a deploy in Elastic Beanstalk. EB would only have to download the image …
> Resolve deployment timeout issues on Elastic Beanstalk

- .travis.yml
- Dockerrun.aws.json
- README.md
- package-lock.json
- package.json
* Images are built in Travis and pushed to Amazon Elastic Container Registry
* Images are pulled from ECR by EB during deployment
*  Resolves deployment timeout issues on Elastic Beanstalk
* Add Travis deployment instructions to readme
> Release 1.13.5 - Resolve deployment timeouts by moving image build from Elastic Beanstalk to Travis

- README.md
- docker-compose.yml
- package-lock.json
- package.json
- src/server/api/user.ts
- src/server/config.ts
- src/server/util/aws.ts
Expose a new endpoint that allows authenticated users to generate pre-signed urls for file uploads.
This feature works with user-level IAM credentials, but the pre-signed URL generated on elastic beanstalk staging does not work, pending some help regarding permission settings for the EB's role.
Before merging, the problem of elastic beanstalk pre-signed links not working should be first fixed.
- `AWS_S3_BUCKET` : The bucket name used for storing file uploads.
- `aws-sdk` : Used to generate S3 pre-signed upload links
> Expose pre-signed upload url endpoint

- src/server/api/redirect.ts
- src/server/util/error.ts
Prerequisite for #10 Transition Page.
- Extract separate functions for get/set operations against the
cache and database
- Convert callback pattern into Promise-based functions for use with
async/await (felt it was cleaner to do this than the [alternative](https://stackoverflow.com/questions/44540022/is-there-any-way-to-inherit-method-signature-with-util-promisify-on-typescript))
- Introduce custom error type with NotFoundError
- Fixed a bug where redirect did not fallback to database if Redis cache
connectivity failed
> Refactor /redirect endpoint in preparation for transition page

- src/server/db_migrations/20200427_add_isFile_column.sql
- src/server/db_migrations/20200428_backfill_isFile_column.sql
We need to introduce a column in the url table to indicate whether a shortlink is pointing to a file.go.gov.sg object.
Create two scripts.  The first would be to add the isFile column in a backwards-compatible way. This is done by making the column nullable(already true by default). After future PRs that update the codebase to start writing into the isFile column, run the second script to backfill and set the not-null constraint.
I'll PR the next step which updates the url model after the migration strategy has been finalised and merged.
> Add `isFile` column in url table

- src/server/api/login.ts
In development mode, we are using `nodemailer-direct-transport` to mail OTPs. But it does not provide consistent mailing performance across different IP addresses. Some IPs addresses may be blacklisted from outbound mailing resulting in errors like [this](https://support.google.com/mail/answer/10336?hl=en). In these cases, developers may not be able to proceed to the OTP and user pages without making code changes.
Since we have a default OTP for local development, and `nodemailer-direct-transport` is a local development only issue, I thought that creating allowing users to proceed to OTP even if mailing fails in development may be appropriate and helpful.
When there is a mail error, I added a conditional statement that checks if the environment is a development environment. If it is, the …
> Proposal to allow user to OTP if mailing fails in development

- src/client/styles/createUrlModal.js
text in input are cut off in iPhone 7 and lower
Closes #3 
specify input `height`
**BEFORE**:
**AFTER**:
Notes:
Checked desktop behavior to ensure it still works.
> fix line height bug in iPhone 6/7

- .eslintrc.ts.json
- src/server/api/user.ts
- src/server/models/index.ts
- src/server/util/aws.ts
We need a way to toggle the visibility of the s3 object. This is because our bucket defaults to `private`. After a short link has been reserved and the file has been uploaded to S3, the client will need to call the edit-url-state endpoint once to trigger this hook, setting the s3 object to `visible`.
Use a hook in the active/inactive edit API endpoint to also toggle the visibility of the S3 object, if the url has `isFile` set to `true`
> Allow S3 object ACL to be toggled when a shortlink is activated/deactivated

- package-lock.json
- package.json
- src/server/api/redirect.ts
- src/server/index.ts
- src/server/util/lrucache.ts
We need a way to not show the transition page multiple times for the same shortUrl.
Use session to store the shortUrl, and read it before deciding to redirect directly or show transition page. Sessions are much easier to work with compared to cookies, as we can see how difficult parsing the cookie was with GA.
> Use session to store shortUrl visits, avoiding repeated transition page redirects

- src/client/components/LoginPage/index.jsx
- src/server/api/user.ts
On shorter desktop displays, the login page graphic may exceed the viewport height. The graphic does not look optimal this way. Furthermore, this affects the placement of the login form on the right as it is vertically aligned by percentage margins.
Added an additional style to limit the maximum height of the graphic.
- Eslint code formatting.
**BEFORE**:
**AFTER**:
> Login graphic height fix

- CONTRIBUTING.md
As described. Just a typo fix to the CONTRIBUTING document, so no need for detailed PR
> Fix GovTech link typo

- .eslintrc.ts.json
- src/server/api/redirect.ts
- src/server/api/repositories/user.ts
- src/server/api/statistics.ts
- src/server/api/user.ts
- src/server/config.ts
- src/server/index.ts
- src/server/models/url.ts
- src/server/util/aws.ts
- src/server/util/ga.ts
- src/server/util/transitionPage.ts
- src/types/server/models/index.d.ts
- src/types/server/util/nodemailer.d.ts
- test/server/api/util.ts
Our eslint config for typescript files does not contain prettier extensions. This leads to conflicting errors between raw eslint and prettier.
Edit the eslint config for typescript to contain prettier extensions.
> Format typescript code with prettier

- jest.config.js
- src/server/api/redirect.ts
- test/server/api/mocks/transitionPage.ts
- test/server/api/redirect.test.ts
With the addition of coveralls, we're able to easily identify untested branches. There were untested branches in the redirect middleware arising from the addition of transition pages.
Add tests with differing results from cookie reducer and user agent string.
- Backend test coverage +1% 🎉
- Resolve uncaught promise rejections in `redirect.ts`
> Add additional tests on redirect middleware

- src/client/components/UserPage/UserLinkTable/UrlTable/EnhancedTableBody/index.jsx
User page table desktop margins and borders were different from the design.
Added minimum widths to enforce spacing and adjusted margins. Added top border to the first row.
**AFTER**:
[Desktop View]
> User page table desktop margins and borders

- src/client/components/UserPage/UserLinkTable/ToolBar/LinkCountHeader/index.jsx
- src/client/components/UserPage/UserLinkTable/ToolBar/index.jsx
The mobile header text for the user page table was missing.
Enabled the header text on mobile and changed its order to place it on a second row.
**AFTER**:
[insert screenshot here]
(PC unchanged)
> User page table mobile header text

- src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/PaginationActionComponent/index.jsx
- src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/index.jsx
- src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/styles.jsx
- src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/styles.ts
- src/client/components/UserPage/UserLinkTable/assets/arrow-left-icon.svg
- src/client/components/UserPage/UserLinkTable/assets/arrow-right-icon.svg
The footer of the user page table has not been updated to the latest design
Updated user page table.
- The position of elements provided by material's footer does not match the design. This was solved by hiding some of the elements and replacing them with our own in ActionComponents.
- To center the page selector, I made the container width 50% and pushed the selector to the right with `margin-left: auto` and then shifted it to the right by half its width to centralize it on the screen.
**AFTER**:
[Desktop](https://user-images.githubusercontent.com/35889982/82580634-f5059a80-9bc1-11ea-96b0-2c7e239938be.png)
> User page table footer

- src/client/components/UserPage/Drawer/ControlPanel/QRCodeModal.tsx
- src/client/components/UserPage/Drawer/ControlPanel/widgets/ConfigOption.tsx
- src/client/components/UserPage/Drawer/ControlPanel/widgets/DrawerTextField.tsx
- Downloading QR code does not show the modal now (made it invisible). Subsequently, I will work on a method that does not involve rendering the QR code on the dom.
- Improved button alignment in drawer in desktop view.
> QR code download and drawer tweaks

- .travis.yml
Specifying the email recipient via environment variable [doesn't actually work](https://docs.travis-ci.com/user/notifications/#how-is-the-build-email-receiver-determined) because notification is determined prior to build, when environment variables are not available.
Revert to default settings where the notification email will be sent to the committer.
> Revert email notifications from Travis to default settings

- src/server/api/login/index.ts
- src/server/api/user.ts
- src/server/index.ts
Joi sends validation errors as a string, which breaks some frontend error handlers that require it to be a specifically-formatted json.
Specify the validator to pass the error to the error-handling middleware. From there, detect whether the error caught was a Joi error, and then format it properly before sending it back to the user.
- Express Joi validator allowing a [passError config](https://www.npmjs.com/package/express-joi-validation#createvalidatorconfig) to be set
- [Custom express error handling](https://www.npmjs.com/package/express-joi-validation#custom-express-error-handler) for Joi
> Fix inconsistent errors sent out by Joi

- src/client/actions/user/index.ts
- src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
- src/client/components/UserPage/CreateUrlModal/styles/createLinkForm.ts
- src/client/components/UserPage/UserLinkTable/UrlTable/EnhancedTableBody/index.jsx
- Upload file button: I have modified the button to use our default themed button, which then provides it a similar background color and hovered background color.
- Link clicks: I have modified the clicks count cell to fit its content. Subsequently, I added an arrowed tooltip on the top-center of this modified cell.
- Toaster for link transfer: There was a double dispatch of snackbar messages for successful link transfers. The solution is to add an `else` statement, so that error messages are only set if the transfer fails.
**AFTER**:
> File client tweaks

- src/client/components/UserPage/UserLinkTable/ToolBar/FilterSortPanel/index.jsx
When filtering with custom queries, a bug occurs when it fetches the page number beyond the max number of entries.
Set the pageNumber to 0 so that we wont go out of bounds.
> Fix filtering bug on multiple pages

- src/client/actions/user.js
- src/client/components/UserPage/UserLinkTable/UrlTable/EnhancedTableBody/index.jsx
- src/client/reducers/user.js
The `updatedAt` column is always updated when clicks are incremented. A change was made in the UI that caused the table to display this column instead of `createdAt`. This created confusion for users.
Revert to displaying the createdAt column instead of updatedAt.
> Display date created rather than date updated in user table

- public/assets/transition-page/styles/transition-page.css
Fixes transition page stylings on IE browsers.
Closes #135.
The problem is that IE browsers do not support CSS variables. Reverting back to hardcoded values solves the styling problems.
**AFTER**:
> IE styling fix for TransitionPage

- src/server/api/logout/handlers.ts
- src/server/api/logout/index.ts
- test/server/api/logout.test.ts
Logout middleware has no unit tests
[Closes #85]
Refactor logout middleware to be seperated into the routes and handler functions so that handlers can be unit tested. Add unit tests for handlers.
> Add unit tests for logout middleware

- package-lock.json
- package.json
- src/server/api/redirect.ts
- src/server/views/transition-page.ejs
- The presence of single-quotes breaks the templating of the long link in Javascript
- Users were only able to visit the link when the refresh button is clicked, as the server interprets teh request as a subsequent visit thereby bypassing the transition page.
Closes #160
- According to RFC3986, single-quotes are reserved in the URI, but
double-quotes are considered invalid, therefore we replace single-quotes
around the template string to double-quotes
- URI-encode the presence of all double-quotes in longUrls during
HTML templating
**Bug Fixes**:
- Resolves an issue where the transition page may not work if the link contains single-quote characters.
> [master] Release 1.17.1 - Patch transition page to allow single-quote links

- Dockerfile
The current Docker image Node v10 is built upon an unmaintained Debian distribution, which can cause security issues.
Closes #155.
Modify Dockerfile to use alpine image. Node version has also been upgraded to 12.
So far, not experiencing any compatibility issues based on testing the core features of GoGovSG. Will test with release checklist tomorrow on staging to confirm it's 100% working.
> Modify Dockerfile to use alpine image

- docker-compose.yml
This is a follow up to #166 , which switches to using port 4566 for localstack
> fix(docker-compose): expose port 4566, the edge server

- src/client/actions/user/index.ts
- src/client/components/CollapsibleMessage/index.tsx
- src/client/components/CollapsibleMessage/styles.ts
- src/client/components/CollapsibleMessage/types.ts
- src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
- src/client/components/UserPage/Drawer/ControlPanel/DrawerHeader.tsx
- src/client/components/UserPage/Drawer/ControlPanel/helpers/reducers.ts
- src/client/components/UserPage/Drawer/ControlPanel/helpers/shortlink.ts
- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
- src/client/components/UserPage/Drawer/ControlPanel/widgets/ConfigOption.tsx
- src/client/components/UserPage/Drawer/ControlPanel/widgets/TrailingButton.tsx
- src/client/components/UserPage/Widgets/FileInputField.tsx
- src/client/reducers/user/types.ts
- src/client/theme/index.js
- src/client/util/requests.ts
Users might want to replace their uploaded files. This PR implements the front-end for replacing files.
- Fixed margins on url drawer
- Fixed url drawer button border colors
- Extend CollapsibleMessage to be able to be absolute positioned if needed
**AFTER**:
[Desktop](https://user-images.githubusercontent.com/35889982/83769599-a4f30180-a6b2-11ea-82ee-ffbaa0a273b8.png)
[iPhone X](https://user-images.githubusercontent.com/35889982/83770202-614cc780-a6b3-11ea-8afa-d817403ef099.png)
1. Replace file with same extension, it should be replaced with the new file
2. Replace file with different extension, long url should change to reflect new extension. Old file should be set to private and new file should be accessible
> Front-end implementation for editing file links

- src/client/util/download.js
Downloading links as CSV does not work on IE as `saveAs` with a blob input does not work on IE11.
Closes [#134]
By changing the blob constructor input into csv  type and changing the string into something recognizable by both IE11 and modern browsers and using msSaveBlob for IE, all supported browsers should be able to download links with the same behavior as before.
1. Download Links on Chrome on develop branch
1. Download Links on Chrome on this branch
2. Download links on IE11 on this branch
3. Both downloads should work. Run a diff between the files from steps 1, 2 and 3, there should be no output.
> Fix download CSV on IE

- Dockerfile
Rendering of fonts for SVG and PNG is not working when we switched to an alpine base image.
The alpine documentation on fonts gives a good list of fonts that we can install to achieve what we need, I'm using GNU FreeFont, with the main reason being that it was what worked with formsg so we've at least tested that it solves font-rendering problems there.
> Install ttf-freefont in alpine image

- scripts/migrate_url_to_user.sql
- scripts/migrate_user_links.sql
The DB schema for both the url and url_history tables have had a compulsory "isFile" column added, but the helper SQL scripts that allow us to migrate short links to users has not been updated to reflect this change. 
Closes #130 
Only the url_history table insertion step needs to be updated to include "isFile", as the actual url table update step only changes the "userId" column.
> Update db migration scripts to include isFile column

- src/client/actions/user/index.ts
- src/server/api/user/index.ts
- src/server/api/user/validators.ts
- src/types/server/api/user.d.ts
At present, two endpoints exist for editing links in GoGovSG. The first allows one to modify the longUrl, and another to toggle the `ACTIVE` or `INACTIVE` state of the link. This can be achieved more efficiently with just one PATCH endpoint.
Closes #121 
To cater to the possibility of old client code being run by some browsers, currently opting to keep the old /url/edit endpoint there for this release, and then remove it in the subsequent one.
> Unify URL edit patch endpoints

- package-lock.json
- package.json
Files can currently be committed without linting, which presents inconvenience to the developer at pre-push or CI since the developer has to add or modify a commit to incorporate the linting. lint-staged is designed to avoid precisely this, `git add`ing any modifications to files (including linting) before commit.
Closes #183
Allow husky to invoke lint-staged so that files that are about to
be committed get automatically linted.
- Update husky, add lint-staged
- Add lint-staged commands to lint-fix files before they are committed
**New dev dependencies**:
- `lint-staged` : as detailed above
> chore(husky): enhance with lint-staged

- .travis.yml
- commitlint.config.js
- package-lock.json
- package.json
Going forward, commits to this repository should follow conventional commits
Enforce commit linting on push, adhering to conventional commits
with exceptions as defined in the commitlint config file
**New scripts**:
- `cz` : invokes commitizen via `git-cz`
**New dev dependencies**:
- `@commitlint/{cli, config-conventional, travis-cli}` : lints commits on push and on Travis
- `commitizen`, `cz-conventional-changelog`: provides a human-friendly interface to compose commit messages via `npm run cz`
> build(lint): add commitlint, commitizen

- src/server/api/links.ts
- src/server/api/sentry.ts
- src/server/constants.ts
- src/server/controllers/RotatingLinksController.ts
- src/server/controllers/SentryController.ts
- src/server/controllers/interfaces/RotatingLinksControllerInterface.ts
- src/server/controllers/interfaces/SentryControllerInterface.ts
- src/server/inversify.config.ts
- test/server/config.ts
- test/server/controllers/RotatingLinksController.test.ts
- test/server/controllers/SentryController.test.ts
Some API endpoints have not been refactored to use the Controller pattern
#156 
This PR continues the refactoring process by refactoring some of the simpler endpoints in the repository.
> Refactor RotatingLinksController and SentryController

- docker-compose.yml
- src/shared/util/validation.ts
- test/shared/util/validation.test.ts
In earlier PRs, we have simplified the localstack endpoint. However, the whitelist is not updated. This prevents the upload of files in development, as localstack urls are not considered valid urls. In addition, our tests and docker-compose file can also be updated or simplified.
- Corrected the whitelist url to `http://localhost:4566`.
- Update tests for whitelist validation to use `http://localhost:4566`.
- Expose only port 4566 for localstack in our compose file.
> fix(localstack): corrected whitelist, test, and compose file

- .travis.yml
This PR allows travis to automatically deploy code changes on the `uat` branch to elastic beanstalk.
> Add UAT deployment to travis

- src/client/actions/user/index.ts
- src/client/actions/user/types.ts
- src/client/components/CollapsibleMessage/index.tsx
- src/client/components/CollapsibleMessage/types.ts
- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
- src/client/components/UserPage/Drawer/ControlPanel/util/shortlink.ts
- src/client/components/UserPage/Drawer/ControlPanel/widgets/ConfigOption.tsx
- src/client/components/UserPage/Drawer/ControlPanel/widgets/DrawerTextField.tsx
- src/client/components/UserPage/index.jsx
- src/client/reducers/user/index.ts
- src/client/reducers/user/types.ts
- src/client/theme/index.ts
- src/server/api/login/validators.ts
- src/server/api/user/validators.ts
- src/server/controllers/UserController.ts
- src/server/db_migrations/20200618_add_description_and_contact_column.sql
- src/server/mappers/UrlMapper.ts
- src/server/models/url.ts
- src/server/repositories/types.ts
- src/server/services/UrlManagementService.ts
- src/server/services/types.ts
- src/server/util/email.ts
- src/shared/constants.ts
- src/types/server/controllers/UserController.d.ts
Before link search can be fully implemented, further collection of data from link owners is required.
#181
This PR implements phase 0 of the implementation for link search. UI Fields and database columns are added for contact information and description for each link.
- Updated URL drawer margins to fit the design more
- Use of negative margins in `DrawerTextField` have been replaced by having helper text in absolute position. The negative margins made it hard to debug element positioning in browser debuggers and calculations of margins needed for subsequent elements were also confusing.
**AFTER**:
[Desktop](https://user-images.githubusercontent.com/35889982/85267034-46e25e80-b4a7-11ea-8913-44cf13ae12ee.png)
[Mobile](https://user-images.githubusercontent.com/35889982/8526 …
> feat: data collection for search

- .eslintrc.ts.json
- src/server/api/qrcode.ts
- src/server/controllers/LoginController.ts
- src/server/controllers/RedirectController.ts
- src/server/controllers/RotatingLinksController.ts
- src/server/controllers/SentryController.ts
- src/server/controllers/StatisticsController.ts
- src/server/controllers/UserController.ts
- src/server/index.ts
Some of the response statements are not followed by a return statement.
- Append return statements to the next line of response statements.
- Also added explicit status code to the existing `res.json` statement.
- Disabled an Eslint rule that removes return statements which it deems unnecessary.
> refactor: append return statements after response callback

- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
- src/server/api/user/validators.ts
- src/shared/util/validation.ts
- test/shared/util/validation.test.ts
When users input descriptions, they're allowed to enter non-ascii characters such as chinese characters. Characters from other languages are not effectively indexed for search. Furthermore, GoGovSg is monolingual at the moment and visitors are unlikely to not know English.
Disallow non-ascii characters on both the input field and backend API validation.
**AFTER**:
There should be an error message and the save button greyed out when a non-english character (e.g chinese) is inputted in the description field.
> feat: disallow non-ascii characters in desc field

- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
Users might not understand what description field is for and write information which is not as useful for search.
Include helpful placeholders and tooltips to nudge users to write descriptions which are useful for members of the public.
> feat: include helpful description placeholder and tooltip

- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
Users might not know what is Go Search in the drawer's description.
Add a hotlink to the faq
> feat: hotlink to faq for gosearch

- src/client/util/requests.ts
- src/server/index.ts
Application is vulnerable to CSRF.
Ensure that the session cookie is not sent when the user visits other domains, by setting the _SameSite_ attribute to `strict`.
Additionally, removed unnecessary custom middleware setting `Access-Control-Allow-Methods` and set `cross-fetch` options from `cors` to `same-origin`.
> CSRF protection

- src/server/controllers/UserController.ts
As of release 1.19, new links are not highlighted on users' url table. This is due to changes in backend response that were incompatible with the frontend implementation
Revert change in behavior in backend response.
Fixes #231
> fix: new link highlighting

- src/client/actions/login/index.ts
- src/server/api/login/index.ts
When an invalid email is used to attempt login, a _HTTP 401 Unauthorized_ should be returned instead of the default _HTTP 400 Bad Request_.
Configure the validation middleware to return _HTTP 401_ if custom Joi email validation fails, instead of handing the error off to Express's `next(error)` as is the default.
This is technically a breaking change, but necessary as we proceed to configure Cloudwatch alerts.
> Use HTTP 401 Unauthorized for invalid login attempts

- src/server/api/index.ts
- src/server/constants.ts
- src/server/controllers/RedirectController.ts
- src/server/views/404.error.ejs
The `/api` route has no default handler. This causes a `504` error to be shown to users when erroneously accessing a link under the `/api` route. Even though this is not a common mistake, it should still show the normal 404 page.
Closes #236 
Add a default handler to `/api` that renders the 404 page.
> fix: render 404 page even on non-existent pages in /api 

- src/server/repositories/types.ts
- src/server/services/UrlSearchService.ts
- test/server/services/UrlSearchService.test.ts
The search API returns some properties that are unnecessary for search.
[Closes #235]
Change the api such that only info necessary are returned. i.e `shortUrl`, `longUrl`, `description`, `contactEmail`.
> fix: remove unnecessary info from search api

- src/server/api/login/validators.ts
Requests to generate/verify OTPs do not log the emails submitted. This information could potentially be important in signalling any malicious activity, and should not be omitted.
Include a log statement right before returning a response to the client.
Logs for the email in question will appear as such:
```bash
app_1         | [0] 2020-07-01 06:04:29 error: OTP verification request rejected due to invalid email:  esanutheous.com
app_1         | [0] ::ffff:172.20.0.1 - [01/Jul/2020:06:04:29 +0000] "POST /api/login/verify HTTP/1.1" 401 "-" "-" - "-" "PostmanRuntime/7.24.1" 119.290 ms
app_1         | [0] 2020-07-01 06:04:42 error: OTP generation request rejected due to invalid email:    esanutheous.com
app_1         | [0] ::ffff:172.20.0.1 - [01/Jul/2020:06:04:42 +0000] "POST /api/login/otp …
```
> Log invalid emails in otp requests

- src/server/config.ts
- src/server/controllers/RedirectController.ts
- src/server/repositories/LinkStatisticsRepository.ts
- src/server/repositories/interfaces/LinkStatisticsRepositoryInterface.ts
- src/server/services/LinkStatisticsService.ts
- src/server/services/RedirectService.ts
- src/server/services/analyticsLogger.ts
- src/server/services/googleAnalytics/index.ts
- src/server/services/googleAnalytics/types/enum.ts
- src/server/services/interfaces/LinkStatisticsServiceInterface.ts
- src/server/util/sequelize.ts
- test/server/controllers/RedirectController.test.ts
- test/server/mocks/repositories/LinkStatisticsRepository.ts
- test/server/mocks/services/LinkStatisticsService.ts
- test/server/services/LinkStatisticsService.test.ts
- Remove link statistics logging code.
- Improvements from @LoneRifle earlier PR [here](https://github.com/opengovsg/GoGovSG/pull/238)
- Move GA page view logging to after page redirect
- Remove link statistics logging, which as of right now is problematic
- Remove GA served events, which can lighten the network load on our servers
> fix: remove link statistics and ga served events

- docker-compose.yml
- src/client/actions/user/index.ts
- src/client/actions/user/types.ts
- src/client/components/BaseLayout/BannerForIE.tsx
- src/client/components/BaseLayout/index.jsx
- src/client/components/BaseLayout/widgets/Banner.tsx
- src/client/components/UserPage/index.jsx
- src/client/reducers/user/index.ts
- src/client/reducers/user/types.ts
- src/server/api/user/index.ts
- src/server/config.ts
- src/server/controllers/UserController.ts
- src/server/controllers/interfaces/UserControllerInterface.ts
We need an additional way to notify link owners of any service degradation or any other important messages.
A banner for the user page that shows important messages to users.
The message is read from the USER_MESSAGE env_var.
**AFTER**:
- `USER_MESSAGE` : user message to be shown. It is optional and the banner will not be shown if this is empty or not supplied.
> feat: user message banner

- src/server/config.ts
`maxMessages` is set at `Infinity`, which encourages long-living SMTP 
connections. This may not work well with services like AWS SES' SMTP
relays, whose machines are ephemeral and may be culled without notice.
Rely on nodemailer's default of 100 messages per [1]. This allows us
to discard and replace connections to better ensure we are talking to
a live connection. Problems with connection leaks were fixed in 
nodemailer 6
References:
[1] - https://nodemailer.com/smtp/pooled/
> fix(nodemailer): use default value for maxMessages

- src/server/controllers/RedirectController.ts
- src/server/services/analyticsLogger.ts
- src/server/services/googleAnalytics/index.ts
- test/server/api/util.ts
- test/server/controllers/RedirectController.test.ts
- test/server/mocks/services/analytics.ts
When a new visitor without a GA cookie visits a short link, the server attempts to set a cookie after a response has already taken place. This results in a HTTP 500 Internal Server Error being logged when in fact a HTTP 302 Redirect has already been returned to the client.
Closes #250
> Fix bug/code smell where GA cookie is set after a server redirect

- package-lock.json
- package.json
- src/server/config.ts
- src/server/controllers/RedirectController.ts
- src/server/services/analyticsLogger.ts
- src/server/services/googleAnalytics/index.ts
- test/server/api/util.ts
- test/server/controllers/RedirectController.test.ts
- test/server/mocks/services/analytics.ts
*You may need to clear your cookies before testing this segment.*
> Release 1.22.1 - GA bugfix, nodemailer config changes

- src/client/actions/login/index.ts
- src/client/actions/login/types.ts
- src/client/components/LoginPage/index.jsx
- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
- src/client/components/UserPage/Drawer/ControlPanel/util/shortlink.ts
- src/client/reducers/login/index.ts
- src/client/reducers/login/types.ts
Closes #204
Frontend email validation with `validator.isEmail`.
- Refactored the login flow from using `IMinimatch` directly, to accepting a function of type signature `(email: string) => boolean`.
**Bug Fixes**:
- UI now checks that user input is an email on the login page.
**BEFORE**:
**AFTER**:
Tested against the following strings:
- "travis .gov.sg"
- "yuanruo@gmail.com;yuanruo@data.gov.sg"
> Patch frontend login email validation

- src/client/components/UserPage/Drawer/ControlPanel/DrawerHeader.tsx
- src/client/components/UserPage/Drawer/ControlPanel/index.tsx
- src/client/components/UserPage/Widgets/CopyButton.tsx
Closes #180 
Update according to the proposed design in https://github.com/opengovsg/GoGovSG/issues/180#issuecomment-645731155
- Change `buttonText` prop in `CopyButton` to be optional, defaults to the url to copy if omitted.
- Removed unused styles
- Destructure props for `CopyButton`
**BEFORE (Desktop)**:
**AFTER (Desktop)**:
**BEFORE (Mobile)**:
**AFTER (Mobile)**:
> feat: display the link user is editing on edit link drawer

- package.json
In development, the current `transpileOnly` ts-node option we are using with ts-node-dev is flagged as a bad option.
Specifically, running the server-dev script throws the following error:
```
app_1         | [0] Using ts-node version 8.10.2, typescript version 3.9.6
app_1         | [0] /usr/local/bin/node: bad option: --transpileOnly
```
The solution which worked for me requires changing the `transpileOnly` option to  `transpile-only`, which is the supported syntax to enable TypeScript transpile only option in ts-node.
> fix: correct ts-node-dev transpile-only option

- src/client/components/BaseLayout/BaseLayoutHeader.jsx
- src/client/components/BaseLayout/index.jsx
- src/client/components/SearchPage/EmptySearchGraphic/index.tsx
- src/client/components/SearchPage/index.tsx
- src/server/config.ts
- src/server/db_migrations/20200720_delete_search_index.sql
- src/server/models/index.ts
- src/server/models/search.ts
- src/server/models/url.ts
- src/server/repositories/UrlRepository.ts
- test/server/config.ts
- test/server/respositories/UrlRepository.test.ts
Links with no description should be excluded from search as some links should not be discoverable.
Add a condition to search to exclude urls with blank descriptions
- Index will be managed by sequelize instead
- Explicit configuration of search weights allow easy reconfiguration either through `config.ts` or env vars
- Empty state graphic should no longer overlap the sort panel
- Nav buttons hidden on search page
**Deploy notes**:
- Run migration script before deploying on production. This will allow sequelize to create the new updated search index in place of the old one.
> feat: index tweaks and exclude blank description from search

- src/client/components/HomePage/index.jsx
- src/client/components/SearchPage/EmptySearchGraphic/index.tsx
- src/client/components/SearchPage/SearchHeader/index.tsx
- src/client/components/SearchPage/SearchResults/SearchTable/SearchTableRow/index.tsx
- src/client/components/SearchPage/SearchResults/index.tsx
- src/client/components/SearchPage/index.tsx
- src/client/components/widgets/GoSearchInput/index.tsx
- src/server/api/search.ts
Certain icon sizes are not in line with the Figma design. Furthermore it is not easy to reach the contact emails on search.
- Allow contact emails to be clickable
- Adjust icon sizes
- Add border to search input on hover
> feat: gosearch ui tweaks

- src/server/repositories/UrlRepository.ts
- test/server/respositories/UrlRepository.test.ts
While the default configuration for parsing queries is set to english on most database configurations and on the local docker image, it might be different in production environments.
For example, in AWS RDS, the default is set to `simple` which does not stem query words.
Explicitly state that the configuration to use in the query is `english`
> fix: explicit parsing config on query

- package-lock.json
- package.json
- src/server/constants.ts
- src/server/controllers/FileCheckController.ts
- src/server/inversify.config.ts
- src/server/services/FileTypeFilterService.ts
- src/server/services/interfaces/FileTypeFilterServiceInterface.ts
- test/server/controllers/FileCheckController.test.ts
- test/server/services/FileTypeFilterService.test.ts
To influence user behaviour, only allow certain types of files to be uploaded
Use file-type and inspection of extension to determine whether
a file can be uploaded
- Bring in file-type as a dependency
- Implement FileTypeFilterService and drop into FileCheckController
- Provide test coverage
> feat(upload): only allow some file types

- src/client/components/HomePage/StatisticsSliver.jsx
- src/client/components/widgets/SortPanel/index.tsx
Closes [N/A]
Adds `key` attribute in a couple of places.
**Bug Fixes**:
Fixes a couple of react errors 
**BEFORE**:
**AFTER**:
N/A
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
N/A
**New scripts**:
N/A
N/A
**New dev dependencies**:
N/A
> feat: some simple fixes that were generating react errors

- README.md
Hand-rolling SQL queries when transferring link ownership is inherently unsafe, and runs the risk of data corruption.
Document the use of tried-and-tested SQL functions, which have been tested safely and are easy-to-use. The functions also take care to track the changes in the `url_histories` audit table.
> Documentation for using SQL functions to transfer link ownership

- docker-compose.yml
- src/server/config.ts
- src/server/controllers/RedirectController.ts
- src/server/controllers/interfaces/RedirectControllerInterface.ts
- src/server/index.ts
- src/server/views/gtag.ejs
- src/server/views/transition-page.ejs
Closes #291 
Tighten how the browser interacts with the rest of the world when
accessing go.gov.sg. Avoid having to inject a nonce into the transition
page by moving the sole inline script into its own templated file.
- specify a content security policy using helmet
- allow requests from Google, Sentry (if present)
- move inline script in transition-page.ejs to its own template, and
map this to `/assets/transition-page/js/gtag.js`
- `CSP_ONLY_REPORT_VIOLATIONS` - when true, only reports CSP violations
- `CSP_REPORT_URI` - the URI that a browser can POST CSP violations to
> feat(helmet): implement CSP policy

- src/server/controllers/interfaces/SearchControllerInterface.ts
- src/server/repositories/UrlRepository.ts
Some search methods lack documentation.
Add documentation for said methods.
> docs: add documentation for search methods

- src/server/api/user/index.ts
- src/server/constants.ts
- src/server/controllers/UrlCheckController.ts
- src/server/controllers/interfaces/UrlCheckControllerInterface.ts
- src/server/inversify.config.ts
- src/server/services/CloudmersiveScanService.ts
- src/server/services/interfaces/UrlThreatScanServiceInterface.ts
- test/server/controllers/UrlCheckController.test.ts
Links submitted by users are not checked for threats, and may be malicious
Use Cloudmersive's Virus Scan API to check URLs submitted by users through 
a new controller
- Rename CloudmersiveVirusScanService to CloudmersiveScanService
- Declare UrlThreatScanServiceInterface and provide
CloudmersiveScanService as an implementation, delegating to the
Virus Scan API client
- Declare and implement UrlCheckController and interface, along with
scaffolding to drop into Express
- Rework inversify config so that a single CloudmersiveScanService is
injected both as a virus scan service and a url threat scan service
> feat(links): scan for threats with Cloudmersive

- src/server/services/CloudmersiveScanService.ts
The Cloudmersive SDK incorrectly specifies the first argument of
`scanWebsite()` as a string, the URL itself; its docs clarify that
it should be an explicit request object. Supply the correct value,
and use `@ts-ignore` to stop TypeScript from complaining
> fix(links): correct website scan API call

- src/server/index.ts
Add Google Tag Manager as a possible image source to pacify our Content Security Policy
> fix(csp): add GTM to img-src

- public/assets/not-found-page/styles/not-found-page.css
- src/server/views/404.error.ejs
The not-found page does not have the SG govt banner at the top, which is an inconsistency in design as all other pages have it.
Follow SGDS's [masthead guidelines](https://www.designsystem.gov.sg/docs/masthead/)
**AFTER**:
> feat(404-page): add sg crest banner

- docker-compose.yml
- src/server/config.ts
- src/server/constants.ts
- src/server/controllers/UrlCheckController.ts
- src/server/inversify.config.ts
- src/server/mappers/SafeBrowsingMapper.ts
- src/server/redis.ts
- src/server/repositories/SafeBrowsingRepository.ts
- src/server/repositories/interfaces/SafeBrowsingRepositoryInterface.ts
- src/server/repositories/types.ts
- src/server/services/SafeBrowsingService.ts
- test/server/respositories/SafeBrowsingRepository.test.ts
The Virus Scan API for websites provided by Cloudmersive was far 
too aggressive, declaring Google Drive links and even a well-known
international organisation as threats. We need a more effective service
that accurately classifies websites that our users link to.
Fixes #377 
Replace Cloudmersive's URL scanning with Google Safe Browsing,
which is more nuanced and more consistent with the browsing experience
for most users, who are probable Chrome users.
- Implement SafeBrowsingService, which vets a given URL against threat
lists maintained by Google. If we have a match, log the match and
declare the URL threat
- Drop SafeBrowsingService into inversify, and wire that into
UrlCheckController
- `SAFE_BROWSING_KEY` - the Google Cloud API key for Safe Browsing …
> feat(links): scan threats with Google Safe Browsing

- src/server/controllers/UserController.ts
Replace file does not update the file extension in the UI.
Closes #261
There was a race condition between the server-side update of the longUrl and the subsequent retrieval of all urls made by the client.
Because we did not await the promise, it returns a success to the client very early (before the update operation completes in the database). This prompts the client to initiate its next step: retrieve all urls and update its redux state. Because the database update operation isnt completed yet, the server returns the old state of urls, causing this bug.
The fix was to await the promise.
> fix(file-upload): race condition caused by not awaiting a DB promise

- src/server/index.ts
- src/server/views/transition-page.ejs
Closes #427 
- Ensure all requested assets are relative to the site root
- Add cdn.jsdelivr.net to the CSP allow list for SGDS resources
- Ensure that only GETs to `/short-url` and nothing else are redirected, everything else is 404
```
::ffff:127.0.0.1 - [19/Aug/2020:01:24:05 +0000] "GET /haha/assets HTTP/1.1" 302 "https://google.com" "-" 80 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" 2.625 ms
::ffff:127.0.0.1 - [19/Aug/2020:01:41:12 +0000] "GET /haha/assets HTTP/1.1" 404 "-" "-" 1780 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" 9.094 ms
::ffff:127.0.0.1 - [19/Aug/2020:01:56:24 +0000] "GET /haha/ HTTP/1.1" 302 …
```
> fix(transition): correct relative paths, redirect middleware

- src/server/controllers/FileCheckController.ts
Winston does not natively handle Error objects when supplied as the sole argument to `error(message: any)`, and as a result, Error does not get properly stringified. Replace with a call to `error(message: string, ...meta: any[])`
> fix(upload): log a message with the Error, not the Error itself

- src/client/components/SearchPage/index.tsx
Closes #323 
- copy `newParams` in `redirectWithParams()`, ensuring that query
is always populated
- for each param in `newParams`, if its value differs from default,
populate in the copy. This results in an object omitting defaults
from the querystring
> fix(search): omit most params in querystring if default

- src/server/index.ts
When shortlinks are distributed, they are occasionally included in sentences and therefore have a period appended to them. Some devices aren't smart enough at parsing these shortlinks and include them in the request, causing 404 errors to occur.
A simple solution would be to tweak the regex of the redirect `.get(...)` middleware to account for a possible trailing period in the shorturl and ignore it in the handler.
> feat(redirect): allow trailing period in shortlink

- src/server/index.ts
Add doubleclick.net to the list of allowed domains for CSP
so that Google Tag Manager and GA can function
> fix(csp): allow doubleclick for img and connect

- src/server/controllers/FileCheckController.ts
- test/server/controllers/FileCheckController.test.ts
Using HTTP 500 Internal Server Error presumes that the problem lies with the server; however
Cloudmersive is clearly rejecting the file as a client error.
Change the HTTP Status Code returned and updated the response message.
> refactor(file-upload): cloudmersive failures now return HTTP 400 Bad Request to client

- test/server/controllers/RedirectController.test.ts
- test/server/mocks/services/analytics.ts
Finally closes #251 , which was also addressed in #94 and others
Provide tests to cover `gtagForTransitionPage()` and cookie
parsing when redirecting a user
> test(redirect): cover gtagForTransitionPage, res.cookie

- src/server/constants.ts
- src/server/inversify.config.ts
- src/server/services/CloudmersiveScanService.ts
- src/server/services/SafeBrowsingService.ts
- test/server/services/CloudmersiveScanService.test.ts
- test/server/services/CookieArrayReducerService.test.ts
- test/server/services/SafeBrowsingService.test.ts
Provide test coverage for services
> test(services): add tests for services

- src/server/views/transition-page.ejs
Browsers eagerly guess the path for apple-touch-icon, triggering 404 alarms for popular links. 
Add a proper reference to what we have, copied from index.html.
> chore(transition): copy apple-touch-icon from index.html

- src/client/actions/user/index.ts
- src/client/components/UserPage/CreateUrlModal/AddDescriptionForm.tsx
- src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
- src/client/components/UserPage/CreateUrlModal/index.jsx
- src/client/components/UserPage/index.jsx
- src/client/components/UserPage/widgets/LinkInfoEditor.tsx
The number of links with descriptions and contact details are low. One way we to address this would be to prompt users to add them after creating their links. This PR serves to redesign the create-url-modal to do that.
Closes #399 
**AFTER**:
> feat(links): redesign create URL modal

- test/server/services/GaLoggerService.test.ts
- test/server/services/SafeBrowsingService.test.ts
As part of routine work to give greater assurances of our codebase,
provide coverage tests for GaLoggerService
> test(services): add coverage for GaLoggerService

- src/client/actions/user/index.ts
- src/client/components/UserPage/CreateUrlModal/AddDescriptionForm.tsx
The toaster message when visibility is updated is not effective.
Reason is that even though the state of visibility has changed, the toaster visually hasn’t, which may be confusing to users. Since the changed visibility state is clearly stated in the edit link panel (Colour changing text), the toaster should just be a confirmation that a change took place.
> fix(searchable-toggle): update toaster message to reflect changes

- .github/workflows/ci.yml
- test/server/services/UrlManagementService.test.ts
As part of routine work to ensure code correctness, add test coverage for UrlManagementService
> test(services): add coverage for UrlManagementService

- src/server/index.ts
CSP implementations vary across browsers, so accommodate 
them by fully specifying the URL, not just the hostnames
> fix(csp): add https: prefix, / suffix

- .github/workflows/ci.yml
Ensure that the infra we use in our build
pipeline is under our direct control
> build(ci): use forks of third-party actions

- src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
Suppress linting warnings by providing default (but helpful) messages
if errors occur when creating links or file uploads
Fixes #563
> chore(create-form): provide default error messages

- src/server/util/sequelize.ts
While GoGovSG uses a variety of postgres-specific queries and features,
the codebase still mostly talks to the database via Sequelize. To facilitate
integration testing, we will have to use something other than postgres,
eg an in-memory embedded database like SQLite.
Remove the hard-coded dialect in Sequelize options and let the dialect
be driven from the database URI. This allows us to easily make use of
other database implementations where needed.
If the hard-coded dialect is kept, integration tests would be limited to
running on CI or an elaborate development environment. Integration tests
_could_ run on a developer environment by mocking the postgres client, but
this is tedious and does not account for potential mistakes in SQL query
syntax or behaviour
> test: remove hard-coded sequelize dialect

- src/server/api/login/index.ts
Prevent abuse of the endpoint responsible for sending OTPs by introducing rate limiting, using the express-rate-limit package already available in GoGovSG. 
Adding rate limits for /otp endpoints. 
For the rate limit, the maximum tries are set to 5 per minute. The numbers are derived from common user's usage. Failing to obtain the OTP up to 3 ~ 4 times in a minute is plausible for normal users. Anything that is 5 and above is likely to be intentional.
> fix: applied rate limit to otp generation and verification

- public/assets/transition-page/styles/transition-page.css
GO Logo intersects with the redirect link
Resolved using CSS. Underneath the image, is there a margin of 24px which causes the logo to intersect with the redirect link when screen height compress. Moving the selector to only trigger in mobile seem to stop that.
##Images
-before
-after
> fix: go logo intersects with redirect link

- src/server/controllers/RedirectController.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/interfaces/UrlRepositoryInterface.ts
- src/server/services/RedirectService.ts
- src/server/services/types.ts
- src/server/util/error.ts
- src/server/views/transition-page.ejs
- test/server/api/util.ts
- test/server/controllers/RedirectController.test.ts
- test/server/mocks/repositories/UrlRepository.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/services/UrlManagementService.test.ts
Closes https://github.com/opengovsg/GoGovSG/issues/546
Implement `getLongUrlAndDescription` to retrieve long url and description for a given short url. It tries to fetch from redis cache first before falling back to fetching from database.
Injecting description meta tag to transition page is done in transition-page template.
Note:
Changes to the format of existing cache value
**Old**
cache key: short url
cache value: long url
**New**
cache key: short url
cache value: JSON.stringify({ longUrl: longUrl, description: description }) 
This change is backward compatible. Old cache value (ie. long url) will fail when it is parsed as json string, throwing `InvalidFormatError`. System will then read from database and update the cache value to the new format. Subsequent read from redis will be …
> Add description meta tag to transition page

- src/client/components/UserPage/UserLinkTable/UrlTable/EnhancedTableBody/index.tsx
Closes https://github.com/opengovsg/GoGovSG/issues/602
The misaligned tooltip is due to the tooltip content taking up the table cell's width as illustrated in the image below. Restructure the html and wrap the tooltip content with an inline-block div fixes the issue.
**BEFORE**:
**AFTER**:
> fix: fix misaligned tooltip

- src/server/controllers/RedirectController.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/interfaces/UrlRepositoryInterface.ts
- src/server/services/RedirectService.ts
- src/server/services/types.ts
- src/server/util/error.ts
- src/server/views/transition-page.ejs
- test/server/api/util.ts
- test/server/controllers/RedirectController.test.ts
- test/server/mocks/repositories/UrlRepository.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/services/UrlManagementService.test.ts
Following discussion with @liangyuanruo , we are reverting this PR given that Go actually redirects crawlers immediately on to the destination, identifying them through `CrawlerCheckService.isCrawler()`
Reverts opengovsg/GoGovSG#610
> Revert "Add description meta tag to transition page"

- src/server/controllers/LoginController.ts
- src/server/controllers/UserController.ts
- src/server/util/response.ts
- src/types/server/api/express.d.ts
The problems are twofold:
1. Login emails can be clearly logged when attempting to login.
2. HTTP 404 Not Found response is technically incorrect when a short link & user email URL object cannot be found. The better security posture is to treat it as an unauthorized attempt to modify a URL that does not belong to said user.
1. Log all emails when OTP verification takes place, for both success and failure cases.
2. Use HTTP 403 Forbidden response if a short link cannot be found by the URL management service.
- Login logging
- Improved security posture
> chore(monitoring): Logging logins, introduce HTTP 403 Forbidden responses when updating links

- src/server/repositories/UserRepository.ts
- src/server/repositories/interfaces/UserRepositoryInterface.ts
- src/server/services/UrlManagementService.ts
- test/server/mocks/repositories/UserRepository.ts
- test/server/repositories/UserRepository.test.ts
- test/server/services/UrlManagementService.test.ts
It is not obvious to the user who they should speak to
when a link they are trying to create already exists. They
often have to turn to support, which then would have to do a
manual lookup via a database query.
If the user attempts to create a link that already exists,
disclose the owner's e-mail
- Declare and implement `UserRepository.findUserByUrl()`
- Lookup owner if link already exists on creation, and disclose e-mail
to user
> feat(links): disclose owner on dup creation

- src/client/components/HomePage/StatisticsSliver.jsx
- src/server/repositories/StatisticsRepository.ts
To stop runaway API calls to /api/stats in development environment on fresh install
Reasons:
1. server returns wrong values
2. client having unlimited retries
Steps involved:
1. opening homepage 
2. in StatisticsSilver.jsx > useEffect runs on mount
3. loadStats() was called
4. checks for any NULL values in userCount, linkCount and clickCount.
5. confirmed that all values are NULL > call /api/stats endpoint
6. received userCount = 0, linkCount = 0 and clickCount = NULL
7. apply changes and re-renders
8. re-rendering triggers useEffect
9. loadstats() called again
10. checks that confirmed that clickCount is NULL > call /api/stats/ endpoint
11. repeat step 6
#659 
To address both the client side and server side issues.
For the client side, we will prevent it from calling the endpoint …
> fix: stop client from repeatedly calling endpoint

- .github/workflows/codeql-analysis.yml
To further strengthen application resilience, 
subject the codebase to the CodeQL so that 
potential vulnerabilities are found and caught
> Add CodeQL static analyser

- src/client/components/UserPage/UserLinkTable/UrlTable/EnhancedTableBody/index.tsx
When user create an extra long link, the user table will overflow and this pushes the other columns out of sight.
Closes https://github.com/opengovsg/GoGovSG/issues/411
Set `maxWidth = 400px` to the `shortUrl` div for viewport bigger than `md`. Also add tooltip to show the full URL when hover above the short URL.
**BEFORE**:
**AFTER**:
> bug: ellipsis for extra long shortened links

- scripts/migrate_url_to_user.sql
- scripts/migrate_user_links.sql
Add the missing `isSearchable` column to the insert statement into `url_histories`
when migrating links via sql fn
> chore(sql-fns): add isSearchable to url_histories insert

- src/client/components/UserPage/AnnouncementModal/index.tsx
Introduce some padding for announcement modal message to provide some alignment
Addresses part of #733
> fix(announcements): tweak padding for message

- package-lock.json
- package.json
- src/client/actions/ga/index.tsx
- src/client/actions/gaEvents/index.tsx
- src/client/actions/login/index.ts
- src/client/actions/search/index.ts
- src/client/actions/user/index.ts
- src/client/components/HomePage/index.jsx
- src/client/components/LoginPage/LoginForm.jsx
- src/client/components/LoginPage/index.jsx
- src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
- src/client/components/UserPage/CreateUrlModal/index.jsx
- src/client/components/UserPage/Drawer/ControlPanel/LinkAnalytics/index.tsx
- src/client/components/UserPage/Drawer/ControlPanel/LinkAnalytics/util/statistics.ts
- src/client/components/UserPage/Drawer/ControlPanel/widgets/DownloadButton.tsx
- src/client/components/UserPage/index.jsx
- src/client/util/download.js
- src/server/api/ga.ts
- src/server/api/index.ts
- src/server/constants.ts
- src/server/controllers/GaController.ts
- src/server/controllers/interfaces/GaControllerInterface.ts
- src/server/inversify.config.ts
To understand user's behaviour, we need to track their actions for both success and error cases with Google Analytics (GA) and Sentry IO
This closes #700 
Send pageview hit to GA on page change
Send event hit to GA on click or state change, for both success and error cases
Send event hit to Sentry on state change for error cases
Error cases will be send to both GA and Sentry for experimentation 
- react-ga
**Features**:
New endpoint to send GA id over to client for react-ga initialisation
GA pageviews:
- home page
- email login page
- otp login page
- link analytics device page
- link analytics clicks page
- link analytics traffic page
- create link modal page
GA events:
- enter home page
- enter login page to fill email
- enter login page to fill otp
- enter user …
> feat: ga and sentry tracking

- src/client/components/BaseLayout/BannerForIE.tsx
- src/client/components/BaseLayout/BaseLayoutHeader.jsx
- src/client/components/BaseLayout/index.jsx
- src/client/components/BaseLayout/widgets/Banner.tsx
- src/client/components/UserPage/Drawer/ControlPanel/DrawerHeader.tsx
1. The banner is suppose to make announcement but it disappears after user scrolls down
2. Text overflow for long 'shorturl' in drawer
Closes #802 
Add an event listener to the page to track the scroll for Y-axis. It will fix the banner's position after scrolling past the mast
**Bug Fixes**:
- add 'overflow: hidden' to the text wrapper
- rename banner's props accordingly
**BEFORE**:
Desktop banner at the top
Desktop banner when user scrolls to bottom
Mobile banner at the top
Mobile banner when user scrolls to bottom
Overflow text before
No overflow text after
> feat: fixed banner

- .github/workflows/ci.yml
Run lockfile-lint from npx, to ensure that the package lockfile
is properly scrutinised with every CI run
> build(ci): add lockfile-lint to CI step

- src/client/components/BaseLayout/BaseLayoutHeader.jsx
- src/client/components/BaseLayout/Masthead.tsx
- src/client/components/BaseLayout/index.jsx
- src/client/components/BaseLayout/widgets/Banner.tsx
- src/client/components/UserPage/AnnouncementModal/index.tsx
IE Banner does not follow the vertical scroll
No tracking implemented for announcement modal
Closes #849 
change the window.scrollY to window.pageYoffset as scrollY is incompatible with IE
change masthead's position to absolute as it does not disappear on scroll in IE
send GA event when announcement modal's button is clicked
IE top view
IE bottom view after scrolling
> fix: banner and tracking

- public/assets/transition-page/styles/transition-page.css
- src/server/views/redirect.ejs
Current skip ahead link only appears after 2 seconds as it was meant for the public to read the message before skipping ahead.
As the number of complains tapers down and transition page drop off has been consistent, this 2 seconds wait should be removed. That means the skip ahead link will appear the moment transition page is loaded.
Closes #877 
Remove the `setTimeout` call and set the CSS of the skip button to be visible from the very beginning.
> feat(tp): remove timeout for skip button

- scripts/migrate_url_to_user.sql
- scripts/migrate_user_links.sql
- src/client/user/actions/index.ts
- src/client/user/components/CreateUrlModal/AddDescriptionForm.tsx
- src/client/user/components/Drawer/ControlPanel/index.tsx
- src/client/user/components/Drawer/ControlPanel/util/shortlink.ts
- src/client/user/reducers/types.ts
- src/client/user/widgets/LinkInfoEditor.tsx
- src/server/api/user/validators.ts
- src/server/controllers/UserController.ts
- src/server/db_migrations/20201116_remove_isSearchable.sql
- src/server/mappers/UrlMapper.ts
- src/server/models/search.ts
- src/server/models/url.ts
- src/server/repositories/types.ts
- src/server/services/UrlManagementService.ts
- src/server/services/UrlSearchService.ts
- src/server/services/types.ts
- src/types/server/controllers/UserController.d.ts
- test/server/api/util.ts
- test/server/controllers/UserController.test.ts
- test/server/mocks/repositories/UrlRepository.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/repositories/UserRepository.test.ts
- test/server/services/UrlManagementService.test.ts
- test/server/services/UrlSearchService.test.ts
Given that GoSearch will be decommissioned, we have to backout its changes.
Start with removing references to isSearchable, and making the index unconditionally index the urls table.
- Revert 4efddc9, and remove references to isSearchable in tests and sql fns
- index shortUrl and desc unconditionally, and copy `urlSearchVector` into `UrlRepository` so that it is easier to
remove `models/search` later on
> refactor(search): remove isSearchable, index conditions

- src/client/directory/index.tsx
The directory page's query string display the entire query parameter. 
Change the query string to display the exact changes
When the link is shared to someone else, the other party will have an easier time identifying the search query and the relevant filters/sort that was applied. 
This will be much harder to do when the entire query parameter is stuck onto the query string.
**BEFORE**:
With query as 'test' and select 'link'
**AFTER**:
With query as 'test' and select 'link'
> refactor(directory): redirect with exact changes in query

- src/client/app/index.tsx
- src/client/app/reducers/index.ts
- src/client/app/store.tsx
Following the [Redux style guide](https://redux.js.org/style-guide/style-guide#only-one-redux-store-per-app), this PR helps to make clear the singleton initialization of the Redux store by placing its creation into its own file and decoupling it from the creation of the React `<Root />` component.
- Greater clarity of Redux store creation
- Greater awareness of the use of the root reducer in Redux
> refactor(redux): move creation of the Redux store singleton into its own file

- README.md
- package-lock.json
- package.json
- src/client/app/store.tsx
Closes #140
Install `redux-devtools` from [Chrome Web Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).
Utilise the [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) library to integrate extension into the application.
**Features**:
Frontend debugging
- Observe store state
- See dispatched actions
- Stack trace
- Time travel
- `redux-devtools-extension` : Simple library to integrate redux-devtools to Redux
> feat: integrate redux-devtools for developer debugging

- .github/workflows/ci.yml
Github actions has [deprecated the feature](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) of setting environment variables via stdout. A workaround of force-enabling it was made during last release, but should be removed whenever possible.
Closes #942
Grab the `$GITHUB_ENV` file from env and append environment variables to it, following the [guide in the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
> fix(gh-actions): set env via GITHUB_ENV instead of stdout

- src/client/app/util/types.ts
- src/client/login/components/LoginForm.tsx
- src/client/login/index.tsx
- src/client/login/reducers/types.ts
- src/client/login/widgets/TextButton.tsx
Migrating jsx files in login folder to tsx files 
- change index, textbutton and loginform to tsx files
- add explicit types for login form variants, including string enums for variants
- change from higher order connect to redux hooks
- change proptypes to typescript
> refactor(login): refactor login page

- src/client/app/components/Section.tsx
Uncaught merge error that cause build to fail 
During development, the login index was still in JSX, thus there was no error.
Once merge, the TSX version throws an error.
Change backgroundType as optional and have default argument of empty string
> fix: backgroundtype as optional

- src/client/login/components/LoginForm.tsx
- src/client/login/index.tsx
The login page and its components were heavily entwined. This made it difficult to reason about interactions and dependencies, or to remove its Redux dependenices.
Part of #955
Refactor the `LoginForm` component to be fully functional. Instead of having inside knowledge of the login flow, it is now configured from outside the component. Instead of hardcoding if-else statements to decide which components to show, it now accepts `children` as props.
It has been upgraded to become a fully controlled component via the `value` prop, whereas previously it was relying on a hack using the `hidden` property to remove DOM input (i.e. user email) when the login page transits from email stage to the OTP stage.
> refactor/login: Refactor heavily-entangled LoginForm component

- src/client/login/actions/index.ts
- src/client/login/actions/types.ts
- src/client/login/components/LoginForm.tsx
- src/client/login/index.tsx
- src/client/login/reducers/index.ts
- src/client/login/reducers/types.ts
Closes #955
Login component state management of email and OTP is now managed by `useState` hooks. The user's email is populated in Redux only upon successful login.
Other minor code improvements were also carried out, such as separating the `useEffect` hooks of login glob validation from that of fetching the login page message.
Unused Redux actions and reducers have been removed.
> refactor: remove keystroke updates to Redux on Login page

- src/client/user/components/Drawer/ControlPanel/index.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/DownloadButton.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/DrawerTooltip.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/FileEditor.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/LinkOwnershipField.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/LinkStateText.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/LongUrlEditor.tsx
- src/client/user/widgets/ConfigOption.tsx
- src/client/user/widgets/LinkInfoEditor.tsx
Drawer domain was implemented and migrated in a way that unnecessarily exposed a lot of implementation. There was a lot of code reimplementation that could have been abstracted for reuse.
Partially fixes #970
- Extract LinkStateText, LinkOwnershipField, LongUrlEditor, FileEditor into their own components.
- Move ConfigOption into DownloadButton's implementation
- Enable reuse of regularText CSS by moving it into ConfigOption
- Move state management into the smallest component subset, which fixed bug #970
> Refactor drawer domain

- src/client/user/components/Drawer/ControlPanel/widgets/LinkStateText.tsx
Fixes #985 
- add a line of text to prompt the user to consider Postman
- line up the state switch to flush with the top of text indicator
> chore(marketing): add nudge to Postman

- package.json
- src/server/modules/user/UserController.ts
- src/server/modules/user/__tests__/UserController.test.ts
- src/server/modules/user/interfaces/UrlManagementService.ts
- src/server/modules/user/interfaces/index.ts
- src/server/modules/user/services/UrlManagementService.ts
Ongoing work for #869 
Use an interface for the ctor argument that usually receives
the UrlManagementService. This allows us to helpfully locate
impls for the argument type using the IDE.
- Create a new interfaces dir with UrlManagementService in it
- Take care with naming to minimise confusion while still keeping
names consistent and clear, despite using identical names for
both interface and impl
Take the trouble also to correct the linting config for the pre-commit hook
> refactor(user): use interface for controller ctor arg again

- package.json
- src/client/directory/index.tsx
- src/client/login/index.tsx
Currently, all private page routes (user and directory) will be directed to login page before redirecting back to the private page, on refresh. Directory page's redirect is coded as an edge case which can be generalised to allow redirect from all private routes
Closes #988 
- Remove directory previous location check and enable all private route 
- Move GA recording for directory to directory page
- Change login defaultprops to typescript default value
> refactor(route): allow all private route to redirect

- src/server/db_migrations/20201207_synchronise_url_clicks.sql
- src/server/models/index.ts
- src/server/models/statistics/clicks.ts
- src/server/models/statistics/daily.ts
- src/server/models/statistics/devices.ts
- src/server/models/statistics/weekday.ts
- src/server/models/url.ts
- src/server/repositories/LinkStatisticsRepository.ts
- src/shared/util/validation.ts
- test/server/api/setup.ts
- test/server/repositories/LinkStatisticsRepository.test.ts
As we are moving forward with features that require bulk database operations, we want to move click count (a frequently updated field) in the URL table.
This is because updating the click count atomically requires a row lock, and it is unlikely that bulk operations will be able to acquire the necessary locks to proceed if a link is being visited constantly.
Part 1 of #984 
Visit our [wiki page](https://github.com/opengovsg/GoGovSG/wiki/URL-Click-Column-DB-Migration) for in-depth discussion of solution.
Proposed migration approach involves multiple phases.
1) Deploy this PR that will let sequelize create a new `url_clicks` table.
2) Run the migration script in this PR that will populate the `url_clicks` table, as well as create the necessary hooks to keep them always in sync.
3) Deploy a …
> Mirror URL table's click column

- src/client/directory/components/DirectoryHeader/DirectoryInput/index.tsx
The arrow in the directory page toggle have been shifted down
Change the css from inline-block to box
**BEFORE**:
**AFTER**:
> fix: directory toggle ui

- src/client/app/util/ga.ts
- src/client/directory/actions/index.ts
- src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTableRow/index.tsx
- src/client/directory/components/DirectoryResults/DirectoryTable/index.tsx
- src/client/directory/components/DirectoryResults/index.tsx
- src/client/directory/index.tsx
Going forward, we need a way to evaluate GoDirectory's search quality.
One of the way is to track the ranking of the results that are clicked by the users and the total results returned by the search query.
Gathering this data will allow us to calculate a meaningful baseline score and set google analytics goals that can be use as benchmark for future improvements.
- Enable google analytics event to record value
- Include result count when recording user's search query
- Record click ranking and its respective query
> Record search result clicks for search evaluation metric

- src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTableRow/index.tsx
- src/client/directory/components/DirectoryResults/MobilePanel/index.tsx
- src/server/repositories/UrlRepository.ts
- src/server/repositories/types.ts
- test/server/controllers/DirectoryController.test.ts
- test/server/mocks/repositories/UrlRepository.ts
- test/server/mocks/services/DirectorySearchService.ts
- test/server/services/DirectorySearchService.test.ts
If we were to allow searching by long link, we should also show the user the long link in the search results.
Closes #1059 
- Include longUrl in the result from endpoint
- Include longUrl in the result found on directory page
- Update directory related tests 
**AFTER**:
Web dashboard
Mobile dashboard
Mobile drawer
> Display longurl in directory page

- src/server/config.ts
- src/server/db_migrations/20201221_remove_url_clicks_column.sql
- src/server/mappers/UrlMapper.ts
- src/server/models/url.ts
- src/server/models/user.ts
- src/server/modules/statistics/repositories/StatisticsRepository.ts
- src/server/modules/statistics/repositories/__tests__/StatisticsRepository.test.ts
- src/server/repositories/LinkStatisticsRepository.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/types.ts
- src/shared/search.ts
- test/server/api/setup.ts
- test/server/api/util.ts
- test/server/repositories/LinkStatisticsRepository.test.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/repositories/UserRepository.test.ts
Part 2 of #984 
**Features**:
1) Deploy application code directly.
2) Once confident that no IO has been made on the Url.clicks column, run the migration script to delete it.
**New scripts**:
- `20201221_remove_url_clicks_column.sql` : The final step in this DB sharding task. Removes all triggers/functions and deletes the Url.clicks column
> Move reading and writing of url table's clicks column to sharded table

- src/client/user/actions/index.ts
- src/client/user/actions/types.ts
- src/client/user/reducers/index.ts
Import bloat in `src/client/user/actions/index.ts` due to actions being stored as constant value strings in `src/client/user/actions/types.ts`
Closes #937
Replace constant value strings with `UserAction` [String Enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) as suggested in issue.
`npm run build` compiled successfully.
First time contributing to this repo, kindly let me if there are areas I can improve in.
> Use enum for user redux actions instead of constant value strings

- public/robots.txt
Keep crawlers away from bundle.js as there are no real links in here
> chore(robots): disallow NLB crawler from parsing beyond the application bundle

- .gitpod.Dockerfile
Gitpod broke with a recent update to pg, which required specifying the user in the database url
Specify the default user for gitpod postgres in `DB_URI`
> fix(gitpod): specify user for DB_URI

- package.json
A recent PR broke the package.json postbuild script, which relied on a hardcoded path
Fix the path
> fix(qr): change postbuild cmd to incorporate assets

- src/server/models/url.ts
- src/server/modules/qr/QrCodeController.ts
- src/server/modules/user/services/__tests__/UrlManagementService.test.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/interfaces/UrlRepositoryInterface.ts
- test/server/mocks/repositories/UrlRepository.ts
- test/server/repositories/UrlRepository.test.ts
There are a few outstanding issues surrounding the url click table migration that needs to be cleaned up.
Closes #1097 
- Change `upsert` to `create` in url's onCreate hook
- Remove unnecessary typecast of the transition object in `create`
- Rename `findByUrl` to `findByUrlWithTotalClicks` for better clarity
> Url click table migration cleanup

- .github/workflows/ci.yml
- src/client/login/actions/index.ts
- src/server/config.ts
- test/server/config.ts
Minimatch is currently used in Go.gov.sg with extglobs disabled, which prevents us from 
expressing a valid glob expression in terms of specific e-mail domains
Part of work for #777 
To facilitate matching of specific domains in e-mail addresses, we have
to configure minimatch to accept extglobs, so that we can match against
a selection of specific domains, eg: `*@+(open|schools).gov.sg`
Take the opportunity to also enable builds to the new edu-focused environments
> fix(minimatch): enable extglobs for e-mail domain whitelists

- .github/workflows/ci.yml
the EB deployment for edu fails because it tries to create an application deployment package that already exists
re-use where possible
> fix(ci): use existing eb package for edu, if exists

- .gitpod.Dockerfile
LocalStack 0.12.x is currently not working with GitPod
Fallback to version that is specified in docker-compose.yml
> chore(gitpod): use last working version of LocalStack

- package-lock.json
- package.json
- src/client/app/components/pages/RootPage/index.tsx
- src/client/app/index.tsx
- src/client/app/store.tsx
- src/client/app/util/download.ts
- src/client/directory/actions/index.ts
- src/client/login/actions/index.ts
- src/client/user/actions/index.ts
- src/client/user/components/Drawer/ControlPanel/LinkAnalytics/util/statistics.ts
- src/client/user/components/Drawer/ControlPanel/widgets/DownloadButton.tsx
Closes #952 
Drop @sentry/react in to replace @sentry/browser
- `@sentry/react` : 1-for-1 replacement for `@sentry/browser`
> feat(sentry): use @sentry/react

- .gitpod.Dockerfile
localstack continues to pose problems for gitpod
roll even further back to localstack 0.11.2
> chore(gitpod): roll even further back to localstack 0.11.2

- src/client/user/components/Drawer/ControlPanel/LinkAnalytics/widgets/DailyStatistics/DownloadClicksButton.tsx
We need a way to track the usage of the newly-implemented link stats CSV download feature. This would help us determine the necessity of things like an announcement modal or other awareness efforts.
A `GAEvent` function already exists for use. Simply send the success/failure events accordingly.
> feat(stats): send ga events for link stats csv download action

- src/client/user/components/Drawer/ControlPanel/widgets/LongUrlEditor.tsx
When editing the long URL in `LongUrlEditor`, the protocol is not automatically stripped. This behaviour does not match that of the link creation modal.
Closes #1092
**Bug Fixes**:
- Strip the protocol from the long URL before updating the state of the `LongUrlEditor`.
**Protocol should be stripped when editing the long URL in `LongUrlEditor`**:
1. Deploy the change
2. Change the long URL of an existing link to one prefixed with `http://` or `https://`
3. The prefix should be automatically stripped
> fix(LongUrlEditor): strip protocol from long URL

- public/assets/not-found-page/styles/not-found-page.css
- public/assets/transition-page/styles/transition-page.css
- src/server/index.ts
- src/server/views/404.error.ejs
- src/server/views/transition-page.ejs
The transition and 404 pages currently have a dependency on
govtech-sgds, delivered via cdn.jsdelivr.com. While convenient, this
needs an entry on our CSP to allow jsdelivr, which malicious actors
might take advantage of.
- Replace govtech-sgds with CSS specific to the masthead, and the
Lion Head Symbol introduced earlier
- Remove jsdelivr entries in CSP
> refactor(pages): drop govtech-sgds via jsdelivr

- src/client/app/components/BaseLayout/index.tsx
Masthead does not show up if `ASSET_VARIANT` env var is not set
Added defaults to use 'gov' as default value for `ASSET_VARIANT`
> fix(masthead): add default asset variant for masthead

- .gitpod.Dockerfile
- Dockerfile
- src/server/modules/qr/services/QrCodeService.ts
Currently, the font used in qr-code generation does not sufficiently distinguish between (capital i) `I`,`1` and (lowercase L) `l`.
Closes #433
Implement IBM Plex Sans as the font for qr code generation instead of the default sans-serif font.
- added appropriate styles to qr generation in `QRCodeService` to render IBM Plex Sans Regular
- added wget command in Dockerfile to install IBM Plex Sans Regular in the container instance to give
sharp access to the font
Note that IBM Plex Sans is sourced from Google Fonts when exporting to SVG, while sharp uses a container-installed instance of the same font from IBM's Plex typeface repository ([link](https://github.com/IBM/plex)).
As such, modifications have been made to the appropriate Dockerfiles to get the container instance to download the …
> fix(qr-fonts): implement ibm plex sans for qrcode url

- .github/workflows/ci.yml
- Dockerfile
Currently, there is no pipeline for the edu variant of go.gov.sg to be built and deployed.
Part of work #777 
- Implemented `build-edu` and `deploy-edu` actions for continuous integration
- Implemented build args for `ASSET_VARIANT` in Dockerfile so that production builds can inject the env var into the container properly
> build(edu-pipeline) implement ci build pipeline for edu

- webpack.config.js
webpack 5 prepends `[ext]` with a `.` in file naming, so remove the 
one we explicitly put in, since we are no longer in webpack 4
> build(webpack): remove spurious . from assets

- webpack.config.js
Currently, webpack 5 builds to target es6 by default, which breaks IE 11 since it only supports up to es5. Additionally, webpack 5 drops quite a few polyfills, which triggers warnings to provide fallbacks even if unused. There is also a transpilation issue with react components where IE would break if the transpilation order was incorrect.
- Changed webpack build target to es5
- Added fallbacks for unused polyfills that webpack 5 drops from webpack 4
- Specified transpilation order to fix an issue with IE, where it would break react components otherwise
> fix(webpack): fix webpack for IE 11 support

- src/client/app/actions/types.ts
- src/client/directory/actions/types.ts
- src/client/home/actions/types.ts
- src/client/login/actions/types.ts
- src/client/user/actions/types.ts
Duplicate boilerplate code exists where Redux actions are present. By addressing this issue, not only will we adhere to the DRY principle, but it will also help ensure that all Redux actions are typed correctly throughout the codebase.
Closes #938
- Implemented generic redux actions interfaces through intersection type extensions
- Refactored redux type definitions to use generic interfaces
> refactor(redux-actions): refactor redux types to use generics

- .gitpod.Dockerfile
- .gitpod.yml
- Dockerfile.maildev-logging
- docker-compose.yml
- src/server/config.ts
Currently, the implementation for maildev does not include support for Gitpod, as maildev is run on another container instance and thus cannot be ported to Gitpod as is. Furthermore, the development workflow is slightly slowed down due to having to get the OTP manually from maildev's visual interface through `localhost:1080`.
By logging the OTP in the console, developers should be able to retrieve the OTP there and log into the application without having to open `localhost:1080`. In addition, this pull request also implements maildev for Gitpod through running a maildev instance on the same container instance.
- logs the OTP in console for logins through maildev during development mode for convenience
- implements maildev support for gitpod
- refactored transport option configurations for …
> feat(maildev): log OTP in console through maildev in dev mode

- src/client/home/components/FeatureListSliver.tsx
The constant defining data to be fed into the featured-by-sliver columns was outside of the export
function, which meant that the i18next.t() function within the const definition was not called
properly at function runtime
Closes #1354
- Shifted the constant to be definted within the export function
> fix(featured-sliver): shift columns const within export function

- src/client/home/components/RotatingLinksGraphic/RotatingLinks.tsx
As exposed by the flakiness in e2e tests, react-typed has undefined behaviour if it receives an empty array of strings. This causes the frontend to throw spurious errors.
Supersedes #1382 , which has further background
Render the react-typed component only if we have an non-empty array of strings
> fix(home): render rotating links only if we have some

- src/client/home/components/StatisticsSliver.tsx
Fixes an error with the statistics sliver copy which would read "public officers onboard" when it should be "education officers onboard"
- implement i18next translation to switch between public and education officers based on current translation.json
> fix(copy): fix statistics sliver copy

- docker-compose.yml
- package.json
- src/client/home/components/RotatingLinksGraphic/index.tsx
- src/server/config.ts
- src/server/models/functions.ts
- src/server/models/statistics/clicks.ts
- src/server/models/url.ts
- src/server/models/user.ts
- src/server/modules/analytics/repositories/LinkStatisticsRepository.ts
- src/server/modules/analytics/repositories/__tests__/LinkStatisticsRepository.test.ts
- src/server/modules/statistics/repositories/StatisticsRepository.ts
- src/server/modules/statistics/repositories/__tests__/StatisticsRepository.test.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/UserRepository.ts
- src/server/util/sequelize.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/repositories/UserRepository.test.ts
Features such as analytics CSV download may prompt a large number of rows to be returned by the database. Too many such queries could exhaust database resources, affecting application stability.
Closes #1304 
Configure sequelize to use read replication. Sequelize's default behaviour of using replicas for read operations is problematic for our use-case because we'd like to default to using the primary DB. In this PR, I propose the use of sequelize's `scope`. We specify a `defaultScope` that contains `useMaster: true`, which acts as a safeguard when contributors forget to include the `useMasterDb` scope. One would have to explicitly use `model.unscoped()` to remove the default `useMaster: true` behaviour.
But this approach is not foolproof, as default scopes also get overwritten when …
> Use read replica for statistics retrieval operations

- .github/mergify.yml
This PR instructs the mergify bot to automatically merge pull requests from
1. dependabot
2. Snyk.io
Pull requests are automatically merged if
1. The proposed upgrade is a non-major version change (dependabot only)
2. All existing CI checks pass
Closes #1418
> feat(mergify): automatically merge bot dependency upgrades

- public/locales/edu/en/translation.json
- public/locales/gov/en/translation.json
- src/client/login/index.tsx
Add a quick liner on go.gov.sg to refer edu users to for.edu.sg.
Closes #1428
**Features**:
- Modify login form to refer school staff with .edu.sg emails to for.edu.sg
> feat(login-form): add referral to for.edu.sg

- .github/mergify.yml
Mergify config was broken owing to the use of `:`, so replace it with a wildcard
> fix(mergify): do not mention : to pacify yaml

- src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTableRow/index.tsx
- src/server/repositories/UrlRepository.ts
- src/server/repositories/types.ts
Exposing the long URL on GoDirectory may reveal sensitive URLs if users are not savvy.
Remove the long URL from both the UI and the `/search` API.
- Users cannot use GoDirectory to mine links for inactive links
> fix/privacy: remove exposure of long URLs from GoDirectory

- src/client/user/components/CreateUrlModal/CreateLinkForm.tsx
Users may upload sensitive content that ends up being discovered by other users on the directory, or indexed by search engines.
Add a suitable message to the creation modal for both link and file creation, that has been endorsed by @lisatjide .
- Users should (hopefully!) think twice about making sensitive documents public.
LInk creation
File creation
> feat/warning: Warn users that their links will be indexable by search engines

- package-lock.json
- package.json
The only way to upgrade sentry is to [bump them both together](https://github.com/getsentry/sentry-javascript/issues/2670#issuecomment-749848872). Dependabot doesn't have that feature so I'm opening this PR manually
> build(deps): bump @sentry/react & @sentry/tracing to 6.5.1

- src/server/api/index.ts
`req.body` is based on user-controlled input and so `req.body.email` could be crafted with a custom .trim() property. Calling .trim() before validating the variable's type is unsafe.
Enforce that the type is a string.
> feat(user-route): validate type of req.body.email

- .gitignore
- package-lock.json
Periodic security patch for the GoGovSG codebase, via `npm audit fix`.
The patch did not upgrade major semvers, on closer examination those were related only to `devDependencies` such as `jest` and `webpack-dev-server`.
> fix/audit: Periodic security patch for the application

- secrets-check.sh
Sorry I had previously fixed the typo with another typo: https://github.com/opengovsg/GoGovSG/issues/1762
See: https://github.com/opengovsg/FormSG/pull/3330
> Fix typo in previous regex

- .github/workflows/ci.yml
- serverless.yml
This PR adds the following deployment actions to our GitHub Actions:
- Deploys GoGov web application to `health-staging` Elastic Beanstalk
- Deploys GoGov web application to `health-production` Elastic Beanstalk
- Deploys GoGov Serverless migration functions to `health-*` Lambda
- Deploys GoGov Serverless migration functions to `edu-*` Lambda
This PR uses the `edu` asset variant in the CI/CD pipeline for building the health environment. We will replace the asset variant in a later PR when the health assets are ready. 
_What tests should be run to confirm functionality?_
Push branch to `edge`
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
1) This PR uses the `edu` asset variant in the …
> chore: add health cicd

- src/server/modules/analytics/repositories/LinkStatisticsRepository.ts
We run multiple instances in production. On initialisation, each instance attempts to upsert a CREATE OR REPLACE FUNCTION. If multiple instances attempts to update the function on the database at the same instance, a `SequelizeDatabaseError: tuple concurrently updated` error can result, as we observed on 6th May during a release. 
This `tuple concurrently updated` occurs because Postgres does not implement locking for DDL on functions, [detailed here](https://www.postgresql.org/message-id/3473.1393693757%40sss.pgh.pa.us), hence such errors can occur when launching multiple instances that all attempt to upsert the function at once.
More details on this can be found in the writeup …
> chore: add transactional lock on CREATE OR REPLACE function

- src/server/modules/threat/FileCheckController.ts
Currently, malicious file upload alerts only logs user ID, which is unhelpful for debugging purposes as we need to retrieve user email and contact them for tracing purposes. Closes #1785
Retrieve user email from session token and logs it in alert for easier retrieval.
> chore: log user email in malicious file upload alert

- .github/workflows/ci.yml
Our Github action workflow [opengovsg/gh-ecr-push@v1](https://github.com/opengovsg/gh-ecr-push/blob/master/main.js) no longer works on Github's Ubuntu 18 virtual machines as the virtual machines [have updated their AWS CLI installation to AWS CLI v2](https://github.com/actions/virtual-environments/commit/17683c89ff78fb10446d23204f908bb888a23730). As a result, the command `aws ecr get-login` ([line 26](https://github.com/opengovsg/gh-ecr-push/blob/5c8dff7f31948b22222e5f2aac5a19074dbb9fa4/main.js#L26)) is deprecated, [causing our CI/CD runs to break](https://github.com/opengovsg/GoGovSG/actions/runs/2547549794). 
Initially, we considered 1) pulling the newest version from the [original …
> fix: replace gh-ecr-push action for aws-cli-v2

- Dockerfile.dev
`npm run dev` doesn't work in M1 Macbook due to Docker build fail. The issue is reported [here](https://github.com/docker/for-mac/issues/6356)
Closes [insert issue #]
**Bug Fixes**:
By updating the dockerfile.dev with `--platform=amd64`, we force the platform to be `amd64` and this seems to fix the build. No other solution has been found on this.
> chore: update Dockerfile.dev to be friendly to M1 Mac machine

- README.md
Go is currently on node 14, but this is not reflected in the readme. Using other node versions may lead to developers having issues with setup or npm installation
Update readme to direct developers to install and use node 14 through nvm
> chore: update readme with node v14 setup

- src/server/serverless/lambda-migrate-url-to-user/index.js
- src/server/serverless/lambda-migrate-user-links/index.js
- src/server/serverless/lambda-migrate-user-links/migrate_user_links.sql
Currently, the lambda functions to migrate links between users always returns the number of rows affected as 1, regardless of the actual number of links transferred.
Closes #1806 
- `migrate_user_links` has been updated to return the actual number of rows affected when updating the `urls` table
- As for `migrate_url_to_user`, it might not be necessary to return the number of rows affected, because if not for an error, there should always be exactly 1 link transferred. Is it ok to just remove this then?
~~I've tested this locally by running the javascript code on node (without using aws lambda, which I'm not sure how to use yet), and locally it seems to work well~~
EDIT: have tested invoking the lambda functions both locally and on staging with the help of @yong-jie and it looks good
> fix(lambda): return correct number of migrated links from lambda functions

- README.md
The readme covers only the gov and edu setups, but not health
Updated the readme to include the health environment
> chore: update readme with for.sg details

- package-lock.json
- package.json
- src/server/modules/auth/services/AuthService.ts
- src/server/util/dogstatsd.ts
We'd like to have custom metrics to count the number of OTP successes/failures, and log down both success and failure cases as well
Notion issue [here](https://www.notion.so/opengov/Add-metrics-logging-for-OTP-emails-sent-37210652dacf4d91ae9ef2186361989d)
Added utility to collect custom Datadog metrics for Go
- Added statsd from `hot-shots` for custom metrics collection (as per the [Datadog documentation](https://docs.datadoghq.com/integrations/node/))
- Added the prefix `go.` to our custom metrics, to differentiate them from other teams' metrics
Added logging for OTP successes/failures and two custom metrics, `go.otp.success` and `go.otp.failure`
- `hot-shots` : client to collect and send custom metrics to Datadog
> feat: add OTP metrics and logging

- src/client/app/helpers/monitoring.ts
We want to connect Datadog sessions on our client with our server traces
Added `allowedTracingOrigins` on our production and staging environments
- Followed the [Datadog documentation](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum) for connecting RUM and traces, and [Redeem's slides](https://docs.google.com/presentation/d/1s1Mho2krp46sdGUNbg8q7-zRDWm_SC-NbIoSSiNfVOQ/edit#slide=id.g11b1a1b1dce_0_296) on setting up front-end tracing
> feat: add datadog client tracing

- src/server/modules/threat/services/FileTypeFilterService.ts
We currently whitelist old Microsoft formats (`.doc`, `.ppt`, `.xls`) for file uploads, but the `file-type` library that we use for detecting file types does not support them ([documentation](https://github.com/sindresorhus/file-type#supported-file-types)), and recognizes them as `.cfb` instead. As Alexis notes, these old formats can also be weaponized and exploited for malicious uses, so we should disallow them anyway
Remove `.doc`, `.ppt`, `.xls` from our `DEFAULT_ALLOWED_FILE_EXTENSIONS`
> feat: disallow file uploads for old Microsoft formats

- .ebextensions/99datadog.config
- .github/workflows/ci.yml
- Dockerfile
- src/client/app/helpers/monitoring.ts
- src/shared/util/environment-variables.ts
- webpack.config.ts
`DD_SERVICE` is not consistently defined for Go across elastic beanstalk, tracing, logs, and monitoring. It's also defined differently from `DD_ENV` even though they serve similar purposes, which may be confusing
Defined `DD_SERVICE` within `ci.yml` in a similar manner to `DD_ENV`, and standardised its naming to `go-[gov/edu/health]` (we should be able to tell whether it's staging or production from `DD_ENV`, so will leave that out of the service naming)
> build: add env variable for datadog service

- src/server/modules/auth/LoginController.ts
Apart from logging down successes/failures for OTP generation, we'd like to do so for OTP verification as well. Currently for OTP verification we have some console outputs - these can be seen on CloudWatch, but moving them to logger will make them also visible on Datadog
Change `console.info` to `logger.info` and `logger.error`
> chore: log OTP verification successes and failures

- README.md
The information about one-time passwords (OTPs) in readme for development is outdated. Maildev is currently being used to obtain OTPs
Updated readme to include information about obtaining OTPs through maildev for development
> chore: update readme about development one-time passwords

- README.md
- Fix typo introduced in previous PR
- Remove unused `pre-release` anchor
- Add newline at the end of the readme document
> fix(readme): typos and unused anchors

- src/server/api/index.ts
- src/server/api/link-audit.ts
- src/server/constants.ts
- src/server/inversify.config.ts
- src/server/models/url.ts
- src/server/modules/audit/LinkAuditController.ts
- src/server/modules/audit/__tests__/LinkAuditController.test.ts
- src/server/modules/audit/index.ts
- src/server/modules/audit/interfaces/LinkAuditService.ts
- src/server/modules/audit/interfaces/UrlHistoryRepository.ts
- src/server/modules/audit/interfaces/index.ts
- src/server/modules/audit/repositories/UrlHistoryRepository.ts
- src/server/modules/audit/repositories/index.ts
- src/server/modules/audit/services/LinkAuditService.ts
- src/server/modules/audit/services/__tests__/LinkAuditService.test.ts
- src/server/modules/audit/services/index.ts
We want to provide an audit trail for link creators, so that they can know who has changed what on their link, and when.
See [Notion story](https://www.notion.so/opengov/As-a-user-I-want-to-know-what-has-changed-on-my-link-and-by-whom-cf452a2d99864ac8850f01e0f6721296) for details on user journey.
We currently store this data in our `url_histories` table. We parse the url records and expose an endpoint for the frontend to retrieve the records.
- Add repository layer to retrieve url records
- Add service layer to parse url records to return pairwise change sets
- Add controller and exposes endpoint `/api/link-audit`
For authenticated query:
```
GET /api/link-audit?url=<shortUrl>&limit=10&offset=10
```
Returns: (JSON) HttpStatus 200 for success
```
{
changes: [ // ordered from most recent
{ …
```
> (backend) Feat/link audit

- serverless.yml
GitHub action for the `edge` branch is failing at the `serverless deploy` step ([example](https://github.com/opengovsg/GoGovSG/runs/8007465383?check_suite_focus=true)). 
Likely because the serverless functions were upgraded to v3 in #1900 which involved removing `excludeDevDepdencies`, but the `capture-ses-events` lambda function from #1913 still had `excludeDevDependencies` that was incompatible with v3
Removed `excludeDevDependencies: true` from `capture-ses-events`, action now passes
> chore(lambda): remove excludeDevDependencies for capture-ses-events

- Dockerfile
- Dockerfile.dev
We have some Dockerfile vulnerabilities from using alpine 3.12 ([Zlib out-of-bounds write](https://app.snyk.io/org/gogovsg/project/a466db86-e13b-4dd1-8b90-2eae048e51da#issue-SNYK-ALPINE312-OPENSSL-2426332), [openssl infinite-loop](https://app.snyk.io/org/gogovsg/project/a466db86-e13b-4dd1-8b90-2eae048e51da#issue-SNYK-ALPINE312-OPENSSL-2426332))
Bump alpine to v3.16, which removes the Dockerfile vulnerabilities
> build: bump alpine to 3.16 in Dockerfile

- src/server/index.ts
HTTP request logs are not being forwarded to Datadog 
Forward logs to Datadog by configuring Morgan, our middleware for logging HTTP requests, to send these logs via `logger.info` rather than the default `process.stdout` (see [Morgan documentation](https://github.com/expressjs/morgan#stream), [Stack Overflow question](https://stackoverflow.com/a/28824464)). 
`logger.info` will then output the logs to both the console and Datadog. The `message` is also trimmed to remove an additional newline inserted by morgan.
- Removed date/time from morgan log format, because `logger` already takes down the time 
After (on CloudWatch):
After (on Datadog):
I blacked out my IP address
> chore: send request logs to datadog

- src/client/login/actions/index.ts
- src/server/modules/auth/LoginController.ts
- src/server/modules/auth/services/AuthService.ts
- src/server/modules/redirect/RedirectController.ts
- src/server/modules/user/UserController.ts
- src/server/modules/user/services/UrlManagementService.ts
- src/server/repositories/UserRepository.ts
We want to collect more useful product metrics for Go
**Features**:
- Set user ID and email for datadog RUM on login, remove user on logout. The user ID/email helps us to track how many unique users are using our app over some time period
- `go.otp.generate.(success/failure)`: number of OTP generation successes/failures. This used to be `go.otp.(success/failure)`, but made it more specific to generation
- `go.otp.verify.(success/failure)`: number of OTP verification successes/failures
- `go.shortlink.clicks`: number of user clicks to existing short links
- `go.shortlink.create`: number of created short links, tagged with `isFile`
- `go.user.new`: number of new users
- Made some logger OTP messages more descriptive with user email
**Problem**:
Note (just FYI): we use …
> feat(datadog): add metrics and set RUM user

- src/client/user/components/CreateUrlModal/CreateLinkForm.tsx
- src/client/user/components/CreateUrlModal/styles/createLinkForm.ts
- src/client/user/components/Drawer/ControlPanel/widgets/FileEditor.tsx
- src/client/user/widgets/ConfigOption.tsx
- src/client/user/widgets/FileInputField.tsx
The `FileInputField` component does not have an inbuilt upload button, which means that every developer using the component has to add their own upload button via the `endAdornment` functionality.
This means that when the component is duplicated, the upload button also has to be duplicated, causing the code to bloat.
Move the upload button into `FileInputField`. 
I've reused the upload button from `CreateLinkModal`. This means that the look and feel of the button in the Drawer modal changes (see screenshots below). Have checked with Feli about this and she is ok with the current design. 
**BEFORE**:
**AFTER**:
> chore: refactor FileInputField component

- src/server/modules/user/UserController.ts
- src/server/repositories/TagRepository.ts
- test/server/repositories/TagRepository.test.ts
The backend should return tag suggestions in both upper and lower cap
Closes [insert issue #]
SQL query to perform LIKE operation on tagKey field and searchText input needs to be in lower cap.
> feat: search for tags in lower cap

- src/server/models/url.ts
- src/server/modules/audit/interfaces/LinkAuditService.ts
- src/server/modules/audit/interfaces/UrlHistoryRepository.ts
- src/server/modules/audit/repositories/UrlHistoryRepository.ts
- src/server/modules/audit/services/LinkAuditService.ts
- src/server/modules/audit/services/__tests__/LinkAuditService.test.ts
Link audit history should return the changes to `tagStrings` as well on the backend
(Did this as a pair programming exercise with @thanhdatle)
- Changed link audit service to consider `tagStrings` as a potentially changeable key
- Changed URL history repository to return `tagStrings` from the URL history
- Minor refactoring: extracted out some repetitive URL into a `mockUrl`
- Changed tests for `LinkAuditService` to include URLs with tag strings
> feat(tagging): add tags to link audit history

- src/server/modules/auth/LoginController.ts
- src/server/modules/redirect/RedirectController.ts
- src/server/modules/user/services/UrlManagementService.ts
- src/server/repositories/UserRepository.ts
- src/server/util/dogstatsd.ts
Follow-up from #1937: names for custom metrics should be extracted and put into a separate file
Made a small refactoring: moved custom metric names into `dogstatsd.ts`
> chore(datadog): refactor custom metric names

- package-lock.json
- package.json
Async 3.2.0 is out of date and needs updating, as seen on our [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5)
Link to [Notion issue](https://www.notion.so/opengov/Security-issue-async-Prototype-Pollution-1d7b6e6cb1654e52b231b49c5f5ee599)
Ran `npm update winston` to bump winston to 3.8.1, which updates async to 3.2.3 and resolves the issue
Tested on dev environment and logging appears to work okay
> build(deps): bump winston from 3.3.3 to 3.8.1

- package-lock.json
- package.json
Dicer 0.3.0 is out of date, as seen on our [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5)
Link to [Notion issue](https://www.notion.so/opengov/Security-issue-dicer-Denial-of-Service-DoS-b83c69647b144d6b9a8dd61b0a169f0e)
Ran `npm update express-fileupload` to bump it to 1.4.0, which removes the dependency on dicer and resolves the issue
Tested file uploads and it works well on dev environment
> build(deps): bump express-fileupload from 1.2.1 to 1.4.0

- src/client/user/actions/index.ts
- src/server/repositories/UserRepository.ts
- test/server/repositories/UserRepository.test.ts
Closes #1978, see problem description in issue 
Backend returns a successful 200 response with body `{ urls: [], count: 0 }` when there's no URLs found, instead of throwing a 404 error with `Urls not found`.
- Handle errors better on the frontend, in cases where the JSON it receives from the backend cannot be parsed
- Updated backend tests to reflect the new changes
- Removed the test case for `throws NotFoundError on findAndCountAll without user`, because it looks to be a duplicate/didn't seem to add much value
> fix: return successful response when no URLs are found

- src/client/user/reducers/index.ts
After a user successfully creates a link with some tags, those same tags will show up again when the user tries to create another new link. This is probably not the behaviour that we want
Set `tags: []` when the user state is reset. Its action is dispatched after a link creation is successful
> fix(tagging): reset tags state after link creation

- src/server/mappers/UrlMapper.ts
- src/server/models/url.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/UserRepository.ts
- test/server/repositories/UrlRepository.test.ts
- test/server/repositories/UserRepository.test.ts
findUrlsForUser function doesn't return urls according to `ORDER BY` correctly
This is due to a common problem found in Sequelize while querying many-to-many rel, this is stil unresolved by now. 
[sequelize-issue](https://github.com/sequelize/sequelize/issues/7344)
The common practice is to write raw query when encountering this bug.
I am keeping the `url_tag` table, in case we need to re-write the query with raw query.
Revised the findUrlsForUser to search for tag by looking for subString in tagStrings column.
> fix: revise findUrlsForUser to return urls in correct order

- src/client/user/actions/index.ts
- src/server/api/user/index.ts
Currently, creating files fails when creating single tags (as opposed to 0 or many). This is due to the behaviour of formdata uploads, which does not interpret a single key-value pair as an array.
- Serialize as JSON in the frontend, and deserialize JSON in the backend.
- Return a bad request if the JSON cannot be parsed in the backend.
(Done w pair programming with @thanhdatle)
> fix(tagging): serialize single tags for file uploads

- public/assets/styles/transition-page/transition-page.css
- src/server/views/transition-page.ejs
hostname in transition page looks wonky in medium widths. fix image size at breakpoints and separate css for each variant
**before**
https://user-images.githubusercontent.com/39296145/191450086-95443fb7-d26d-470b-af39-11980dc4c34c.mov
**after**
https://user-images.githubusercontent.com/39296145/191450108-6b82b336-265b-4336-9e4b-37a801ea401a.mov
**before**
https://user-images.githubusercontent.com/39296145/191450152-108ddd3a-f606-4336-998e-44615b8bdaf9.mov
**after**
https://user-images.githubusercontent.com/39296145/191450176-c90cc182-1cfd-4fe7-a0b7-ac9cfa5333fc.mov
**before**
https://user-images.githubusercontent.com/39296145/191450466-18063110-801f-4bef-8282-d10d1cdbbde2.mov
**after**
https://user-images.githubusercontent.com/39296145/191450251-8dc9caf1-1fc2-482e-9886-da83fb06e790.mov
> fix: host name display out of alignment with graphic

- src/server/repositories/UserRepository.ts
- src/server/util/sequelize.ts
- test/server/repositories/UserRepository.test.ts
Closes #1994, see problem description in issue
Created function to escape wildcard characters like `_`, `%`, `\`, and used it to escape underscores in tags at the repo layer before searching. Credits to [this StackOverflow Q&A](https://stackoverflow.com/questions/42519805/how-to-escape-like-wildcard-characters-and-in-sequelize)
Added a test to ensure that underscores are escaped correctly in the where conditions passed to Sequelize
> fix(tagging): escape searching by tags with underscores

- src/server/api/user/index.ts
- src/server/api/user/validators.ts
- src/server/modules/bulk/BulkController.ts
- src/server/modules/bulk/__tests__/BulkController.test.ts
- src/server/modules/bulk/services/__tests__/BulkService.test.ts
- src/server/modules/threat/services/SafeBrowsingService.ts
- src/server/modules/threat/services/__tests__/SafeBrowsingService.test.ts
- src/server/modules/user/interfaces/UrlManagementService.ts
- src/server/modules/user/services/UrlManagementService.ts
- src/server/modules/user/services/__tests__/UrlManagementService.test.ts
- src/server/repositories/UrlRepository.ts
- src/server/repositories/interfaces/UrlRepositoryInterface.ts
Currently, when we bulk create links, we do not accept tags as input.
This PR adds backend functionality for tagging on bulk creation. Specifically, this PR adds functionality to accept tags as input on bulk creation, upsert tags, and add the tag-url mapping. 
This PR also refactors SafeBrowsingService to clean up duplicated logic.
> feat: backend/bulk tags

- src/client/user/widgets/TagsAutocomplete.tsx
The error message for invalid tags on the create new link modal currently does not include underscores in its description.
Add underscores to the error message for invalid tags.
**BEFORE**:
**AFTER**:
> fix(tagging): include underscores in error message for invalid tags

- src/server/serverless/lambda-migrate-url-to-user/migrate_url_to_user.sql
- src/server/serverless/lambda-migrate-user-links/migrate_user_links.sql
When using lambda functions to transfer links, the url history records created should contain the `tagStrings` as well
Add `tagStrings` as a column to be inserted into `url_histories` in the SQL scripts
- Post deploy: the SQL functions need to be updated
> chore(lambda): update sql scripts for transferring links with `tagStrings`

- src/client/user/components/CreateUrlModal/CreateLinkForm.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/TagsEditor.tsx
- src/client/user/widgets/TagsAutocomplete.tsx
Currently, adding tags requires the user to press enter, which can be non-obvious and unintuitive. 
Allow tags to be added when the user presses enter, space, comma, or clicks away from the tags input.
~But a slight ordering problem happens when the user clicks away from the tags input to the "create link" or "save" button at one go:~
~- When the user clicks "create link" on the create link form, first the tag input is added, then the link is created;~
~- When the user clicks "save" on the edit link form, first the link is saved, then the tag input is added.~
edit: above problem is fixed, always adds tags before saving. but the solution might be a little unclean though
Some extra fixes: slight amendments to logic for disabling save/create link buttons
> fix(tagging): allow tags to be added on space, comma, clickaway

- src/client/user/widgets/TagsAutocomplete.tsx
The decision is to just stick with clearing the tag input when a tag is removed. However, the underlying React state for the tag input is not cleared even when the input looks to be cleared, so we need to clear the state as well.
Closes #2027
Clear tag input state (and tag suggestions) when the user removes a tag.
> fix(tagging): clear tag input when tag is removed

- src/client/user/components/CreateUrlModal/CreateLinkForm.tsx
- src/client/user/components/Drawer/ControlPanel/widgets/TagsEditor.tsx
- src/client/user/widgets/TagsAutocomplete.tsx
See issue description in #2026
Closes #2026 
On the edit link form, ensure that the tags field is aligned with the save button, by fixing the helper text's position so that it does not take extra height.
However, we need a way to toggle between making the helper text add extra height on the create link form, and adding no height on the edit link form. This is done through the use of the boolean variable `fixHelperTextPosition`.
**Before**:
Create link form
https://user-images.githubusercontent.com/41856541/195542387-27999e00-1dae-4a16-aad7-3336e54b5943.mov
Edit link form
https://user-images.githubusercontent.com/41856541/195542566-2cdc6bc8-5fdd-49c8-90c1-7d2de418589a.mov
**After**:
Create link form: unchanged from before
Edit link form …
> fix(tagging): align error text with save button on edit link drawer

- src/client/user/widgets/TagsAutocomplete.tsx
Currently, clicking on the 'x' on a tag on the create/edit link forms is the only way to remove the tag. Backspace doesn't do this, which may be unintuitive or non-keyboard friendly.
See [Notion issue](https://www.notion.so/opengov/Update-Delete-should-delete-the-tag-ae73e761415e4ac1874965316a7e7444)
Allow backspaces to remove tags.
> feat(tagging): allow backspaces to remove tags

- src/server/modules/threat/FileCheckController.ts
- src/server/modules/threat/UrlCheckController.ts
- src/server/modules/user/services/UrlManagementService.ts
- src/server/util/dogstatsd.ts
Currently, the metrics for malicious activity are defined under metric filters for CloudWatch log groups. (See [AWS console](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Faws$252Felasticbeanstalk$252Fgo-production$252Fvar$252Flog$252Feb-docker$252Fcontainers$252Feb-current-app$252Fstdouterr.log$23metric-filters) for more details, requires AWS permissions to access)
The current approach presents several problems:
1. We cannot distinguish between malicious links and malicious files being uploaded
2. We cannot distinguish between staging/prod and gov/edu/health services without giving each metric a different name
3. The metrics are not defined in the codebase, so it's not under version control, and it adds some 'hidden' …
> chore(datadog): add metrics for malicious file or link activity

- src/server/index.ts
Closes #1961
Check the incoming error code, type and syntax error. If 400 is received, return 400 back
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
[insert screenshot here]
**AFTER**:
[insert screenshot here]
_What tests should be run to confirm functionality?_
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
- `env var` : env var details
**New scripts**:
- `script` : script details
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
> feat: json parsing error

- src/client/app/util/format.ts
- src/client/home/components/FeatureListSliver.tsx
- src/client/login/index.tsx
- src/client/user/components/AnnouncementModal/index.tsx
The announcement modal currently does not allow HTML inside its message, preventing us from using clickable hyperlinks.
Allow HTML for the announcement modal message. Since we control the announcement message (through the `ANNOUNCEMENT_MESSAGE` env variable), this should be safe.
- Sanitize message before setting it in inner HTML
- Changed from `display: flex` to `display: block` to avoid new HTML elements from being added in new columns
- Fixed small typo by renaming `hmtlSanitizer` to `htmlSanitizer`
**AFTER**:
`ANNOUNCEMENT_MESSAGE` here is set to `You can now tag your links and manage your dashboards effectively. Learn more about this on <a href="https://guide.go.gov.sg/guide-1/link-tagging">our guide</a>.\nFurthermore, our team is constantly looking for new problems to solve for our …
> feat: allow html for announcement modal message

- package-lock.json
- package.json
`sharp` 0.30.5 is out-of-date: it depends on an old version of an `ansi-regex` that contains a ReDoS vulnerability (see [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-ANSIREGEX-1583908))
`sharp` is currently used for image resizing for QR codes
Update `sharp` to 0.30.7
> build(deps): bump sharp from 0.30.5 to 0.30.7

- package-lock.json
- package.json
`bcrypt` 5.0.1 is out-of-date: it depends on an old version of an `ansi-regex` that contains a ReDoS vulnerability (see [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-ANSIREGEX-1583908))
`bcrypt` is currently used for hashing and cryptography for OTPs
Update `bcrypt` to 5.1.0
> build(deps): bump bcrypt from 5.0.1 to 5.1.0

- src/server/repositories/UrlRepository.ts
- test/server/api/util.ts
Directory searches for links are not paginated at the database level. Instead, the server fetches all of the links from the database at one go (then counts and slices it afterwards). This can potentially create immense server load If there are many links returned from the search query.
Paginate directory searches for links (both by keyword and email) at the database level.
- Use `LIMIT` and `OFFSET` for the main query
- Add a separate query to fetch the total count of links
An alternative approach considered was to convert the raw queries to Sequelize and use `findAndCountAll` - but Sequelize  queries aren't powerful enough to support full-text searches, so for consistency I decided to leave them all as raw queries.
For unit tests: I repurposed the `count(*)` mock query result to return …
> chore: paginate directory search

- src/client/user/components/EmptyState/isFiltered.ts
- test/end-to-end/UserPage.test.ts
- test/end-to-end/util/helpers.ts
To reproduce:
- Login and go to the user page, ensure that you have some links
- Search for a non-existent tag
- Search bar disappears and page says that you have no short links
Regression likely introduced by #2037, by separating `searchText` out into `searchText` and `tags`
Closes [Notion issue](https://www.notion.so/opengov/Address-bug-when-searching-for-tag-that-does-not-exist-b6c77f13eac149d796881c93f45921c0)
Change the condition for determining if the user has searched/filtered for URLs, by also checking for the existence of `tags` in `tableConfig`
**BEFORE**:
When searching for a non-existent tag:
**AFTER**:
When searching for a non-existent tag:
Also shortened the wait time for searching for tags from 3s -> 2s, which still seems more than long enough. Wait time for searching for …
> fix(tagging): fix filtering for no results when searching by tags

- src/client/user/actions/index.ts
- src/server/api/user/validators.ts
- src/server/modules/user/__tests__/UserController.test.ts
The query conditions for `state` when searching for URLs in the user page are overly permissive, and should be restricted to either active or inactive states.
See [Snyk dashboard - Improper Type Validation](https://app.snyk.io/org/gogovsg/project/195ed33d-81b4-40d4-9918-45609ce999fb#issue-dbdfdd86-c468-4c17-aef0-d0c9b0bad893)
Use Joi validator to allow the optional `state` field to be only one of `ACTIVE`, `INACTIVE` ~or `''`.~
~I'm perhaps less comfortable with allowing `state` to be `''`, but the frontend inserts `&state=` by default so disallowing it will break the frontend search~ edit: removed `''` from `state` following the comments below!
**Tests**:
- Added tests for an invalid and empty `state` field in `UserController.test.ts`
- (Improvement) Renamed test cases that return a bad …
> fix: restrict state to active and inactive in url search

- src/client/directory/actions/index.ts
- src/server/api/directory.ts
Similar to #2050, the query conditions for `state` when searching for URLs in the directory page are overly permissive, and should be restricted to either active or inactive states.
See [Snyk dashboard - Improper Type Validation](https://app.snyk.io/org/gogovsg/project/195ed33d-81b4-40d4-9918-45609ce999fb#issue-dbdfdd86-c468-4c17-aef0-d0c9b0bad893)
Use Joi validator to allow the optional `state` field to be only one of `ACTIVE`, `INACTIVE`. (updated to remove `''` following comments in the other PR!) (Joi validated fields are optional by default)
No controller tests can be added here - the Joi validation happens in the middleware before hitting the controller level
> fix: restrict state to active and inactive in directory search

- src/server/repositories/UserRepository.ts
Bulk-created links with the same `createdAt` time are not necessarily returned in the same order when sorting links by `createdAt` only. This may cause issues, like the sort order of bulk links suddenly changing when one of the links is updated
See [Notion issue - [Create] Link sort order seems to be changed after adding the tag](https://www.notion.so/opengov/Create-Link-sort-order-seems-to-be-changed-after-adding-the-tag-62912d3cae88455a957e4955d51ca984) and [Notion issue - [Create] [Update] Link status changes after adding or updating the tag](https://www.notion.so/opengov/Create-Update-Link-status-changes-after-adding-or-updating-the-tag-c251902d44754ab08d832e122ff8bff6)
Add a second `ORDER BY` condition on `shortUrl`, leading to a deterministic ordering with bulk-created links
- …
> fix: add second order by shortUrl when searching for links

- package-lock.json
`postcss` 8.4.5 is out-of-date: it depends on an older version of `nanoid` that has a vulnerability (see [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-NANOID-2332193))
`postcss` is used by `sanitize-html`, which is used to sanitize HTML inputs in two places: login whitelist phrase, and home page target users phrase
Within `package-lock.json`, I deleted the chunk with `postcss` version 8.4.5, then re-ran `npm install`. This generated the new `package-lock.json` as seen in this PR with `postcss` version 8.4.18
> build(deps): bump postcss from 8.4.5 to 8.4.18

- package-lock.json
According to our [Snyk dashboard](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-ANSIREGEX-1583908), there's an ansi-regex vulnerability that is introduced by the package `wide-align@1.1.3`, which uses `string-width@1.0.2`.
Update the dependencies for `wide-align` v1.1.3 to use `string-width` v2.1.1 instead of v1.0.2.
- This was done by deleting the block for `wide-align` v1.1.3 in `package-lock.json`, then running `npm install` to regenerate `package-lock.json`
- Tested locally and it looks fine
- Should probably test on staging eventually
> build(deps): bump dependencies for wide-align 1.1.3

- src/server/config.ts
NODE_ENV is set to production in both Staging and Production environment, causing apiEnv to have `live_` prefix in both staging and prd
To make apiEnv to rely DD_ENV instead.
> fix: set apiEnv according to DD_ENV instead of NODE_ENV

- src/server/modules/api/external-v1/ApiV1Controller.ts
- src/server/modules/api/external-v1/__tests__/ApiV1Controller.test.ts
- src/server/modules/user/UserController.ts
- src/server/modules/user/__tests__/UserController.test.ts
- src/server/modules/user/services/UrlManagementService.ts
- src/server/modules/user/services/__tests__/UrlManagementService.test.ts
- src/server/util/error.ts
One can manually submit a request (`PATCH /api/user/url`) to update the `longUrl` for a file, or the `file` for a link. This should not be allowed.
Disallow updating files for links and links for files at the service layer, depending on the `isFile` field of the URL.
- Return a 400 bad request on the user and API controller when encountering this error
- Created a new error type `InvalidUrlUpdateError` for this, because it didn't seem to fall under any existing error type - not sure of my approach though, happy to modify where necessary
> fix: disallow updating files for links and links for files

- public/locales/edu/en/translation.json
- public/locales/gov/en/translation.json
- public/locales/health/en/translation.json
api documentation is pointing to the wrong URL
Closes [insert issue #]
updated translation.json files in 3 envs to point to the correct API doc URL. E.g: https://guide.go.gov.sg/developer-guide/api-documentation
> fix: updated api-doc urls

- docker-compose.yml
`docker-compose.yml` is using `localstack:latest`, which has recently bumped its latest version from v1.2.0 to v1.3.0. Apparently the local AWS bucket somehow does not work the same way in `localstack` v1.3.0, and hence file uploads and E2E tests are failing.
Fix the version of `localstack` to 1.2 in `docker-compose.yml`.
(If we want to upgrade to `localstack` v1.3.0 eventually, we'll have to figure out how to make local S3 work with it.)
Other notes:
- Integration tests are helpful for debugging!
- Try pinning down specific versions of images instead of using `latest`, because it makes the project vulnerable to package upgrades which may suddenly and inexplicably break things
- Curiously I still can't replicate this problem locally, despite killing all docker containers and restarting …
> build: fix localstack version in docker-compose to 1.2

- src/server/modules/user/services/ApiKeyAuthService.ts
- src/server/modules/user/services/__tests__/ApiKeyAuthService.test.ts
- src/server/util/dogstatsd.ts
We want metrics to track API key generation
Add datadog metrics to track API key generation, and whether these API keys are new or not. This will incur an extra database read, but the cost is probably quite small in the grand scheme of things
> chore(datadog): add metric for generating API keys

- README.md
- docker-compose.yml
- src/server/config.ts
It's really tiring for devs to have to log in again every 30 mins
Change the default `COOKIE_MAX_AGE` from 1800000 (30 mins) to 86400000 (1 day) in `docker-compose.yml`.
- `COOKIE_MAX_AGE` is already set to 86400000 on gov/edu/health prod, so there will be no change at all to production
- I could not find any history as to why `COOKIE_MAX_AGE` was set at 30 mins 3 years ago, but since prod already overrides this to 1 day anyway, I figure that bumping everything to 1 day by default is fine
> chore: change default session cookie max age to 1 day

- src/server/modules/audit/LinkAuditController.ts
- src/server/modules/user/UserController.ts
In two places in the codebase, the server does not return immediately after making a response, leading to `res.send()` being called _twice_, which causes an unhandled promise rejection. This is still okay for node <14 because it just gives a warning, but not from node 15 onwards (see [node 15 release docs](https://nodejs.org/en/blog/release/v15.0.0/#throw-on-unhandled-rejections-33021)) as it throws an error and terminates the entire node process, which is very scary.
Example error message:
- In `UserController`: simply add `return`
- In `LinkAuditController`: had to invert the logic a little to do the same functionality without calling `res.send()` twice
> fix: add return after making server response

- src/server/modules/threat/UrlCheckController.ts
- src/server/modules/threat/services/SafeBrowsingService.ts
- src/server/modules/threat/services/__tests__/SafeBrowsingService.test.ts
Safe browsing errors are not being logged and returned properly. 
The returned error message looks like this, because `response` and `response.body` are objects:
The logged error message looks like this, because it's trying to log `error` instead of `error.message`:
- Change the error message contents from `response` and `response.body` to `body.error.message`
- Change the logged error message from `error` to `error.message`
Now, both the logged and returned error messages look like this:
For context, when calling the Safe Browsing API, the reponse JSON `body` looks something like this when there's an error:
The indentation changes from line 83/84 onwards in this PR are caused by prettier
Also, apologies to the team for unintentionally exposing the now-removed API key 🙇
> fix: update safe browsing error messages

- src/server/api/user/validators.ts
- src/server/modules/api/external-v1/ApiV1Controller.ts
- src/server/modules/user/UserController.ts
- src/server/modules/user/__tests__/UserController.test.ts
- src/server/repositories/UserRepository.ts
- src/server/repositories/types.ts
We want to clean up validations for getting URLs on the internal API, as noted in #2073 
Improved the validations for getting URLs on the internal API (user controller).
Validations
- Joi validations are clearer in terms of what they expect from each of the params
- Removed `updatedAt` as an option for `orderBy`, since it's unused
- Added optional XOR between `searchText` and `tags` to ensure that both are not used at the same time
- Add `lowercase()` to `searchText`, since we want to convert it to lowercase anyway
User controller
- Set default `orderBy` option to `createdAt` rather than the unused `updatedAt`
- Make `searchText` and `tags` optional params to pass down to the URL management service and URL repository
> chore: refactor validations for getting urls

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Ubuntu runner image is currently at version 18.04, which is deprecated.
Closes #2111
Upgrade to using Ubuntu version 22.04 in `ci.yml`.
Have also changed `ubuntu-latest` to `ubuntu-22.04` in `codeql-analysis.yml` to avoid the use of `latest`, which may potentially spring nasty surprises some day.
> build(deps): bump ubuntu from 18.04 to 22.04

- src/server/config.ts
Integration tests on local dev (e.g. #2091) can make many user logins within a short time period, and if the OTP rate limit is too low, the logins will fail
Disable OTP rate limiting on local dev. Setting the max rate limit to 0 disables it entirely (see [`express-rate-limit` documentation](https://www.npmjs.com/package/express-rate-limit#configuration))
> chore: disable otp rate limit on local dev

- src/server/modules/analytics/services/DeviceCheckService.ts
- src/server/modules/analytics/services/__tests__/DeviceCheckService.test.ts
tldr; our server is wrongly classifying google's page renderer bot as a user on "Desktop", when it should be classified under "Others" instead. full story:
- Recently, a user sent out a Go link to many users via SMS. Unexpectedly, they saw that in their link statistics section, there were many more hits than expected and 90% of them were coming from desktop, when all their actual human users should be coming from mobile instead (since they're opening the link from SMS). 
- Upon investigating our logs, we can see from the user-agent string that these requests are being made by the "Google-PageRenderer" bot, whose purpose is presumably to automatically render pages from links sent out by SMS. Due to incomplete bot-handling logic on Go, these hits were wrongly categorised under "Desktop", …
> fix: identify google page renderer user agent as a bot

- test/integration/api/external-v1/Urls.test.ts
- test/integration/api/user/Urls.test.ts
- test/integration/config.ts
- test/integration/util/db.ts
- test/integration/util/helpers.ts
- test/integration/util/requests.ts
We'd like to add integration tests for our external API URLs
Add integration tests for our external API to create, get, and update URLs at the `/api/v1/urls` endpoint.
-  The strange `;( ... )` syntax in e.g. `;({ email, apiKey } = await createIntegrationTestUser())` was enforced by prettier, see   [this comment](https://prettier.io/docs/en/rationale.html#semicolons) in their docs
- There's some duplication in logic for creating the API key, which seems unavoidable because the test environment is set up differently from the server
- ~inb4: I hope GitGuardian doesn't complain loudly about the `API_KEY_SALT` variable, it's used in local dev only~ surpisingly it looks like we're in the clear!
> test(api): add integration tests for external api urls

- src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTableRow/index.tsx
- src/client/directory/components/DirectoryResults/MobilePanel/index.tsx
Part of the link transfer feature (see [Notion doc](https://www.notion.so/opengov/20230309-Link-Transfers-4450fc62cba84a91862b130055d5abeb?pvs=4))
This PR adds a "Request ownership" button to the directory table. On mobile, the button will not be shown on the table but only appears in the bottom panel (after the user clicks on the table row).
Clicking on "Request ownership" will take the user to Go's [Contact Us form](https://form.gov.sg/62f0747c7da3e1001240f8bb). In the future, clicking it should instead create an actual link transfer request and send an email out to the link owner, but as a first step we've agreed with product-side to redirect them to the contact form first.
**Notes**:
Ideally, the "Request ownership" button should be an actual `Button` component instead of a `Link`, …
> feat(link-transfer): add request ownership button to directory table

- src/server/serverless/bulk-qrcode-generation/index.js
- src/server/serverless/bulk-qrcode-generation/s3.js
The error messages on the Lambda were not sending successfully to the server as the error object was in the wrong shape (object instead of string).
This PR is a quick fix to change the shape of the error object.
> chore: fix error messages

- .github/workflows/ci.yml
GitHub action for integration tests is not running because it's using Ubuntu 18.04, which is [deprecated as of April 2023](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
This is blocking for any deployment/release because the build and deployment steps cannot happen before integration tests pass
Apologies, when merging in the integration tests PR #2091 (which was first opened before the ubuntu upgrade PR #2133), I didn't realise that the GitHub action was outdated
Bump Ubuntu version from 18.04 to 22.04
> build: update ubuntu to 22 in integration tests

- README.md
- docker-compose.yml
- src/client/user/actions/index.ts
- src/client/user/actions/types.ts
- src/client/user/components/AnnouncementModal/index.tsx
- src/client/user/reducers/types.ts
- src/server/config.ts
The button text on the announcement modal is fixed to "Try me now", but we want it to be configurable
Add a new env var `ANNOUNCEMENT_BUTTON_TEXT` that allows configuration of the announcement modal's button text. If not set, the button's text will default back to "Try me now".
Also changed `width` to `minWidth` on the button styling, since the button text could overshoot the width limit and be wrapped across multiple lines, which we probably don't want?
**BEFORE**:
**AFTER**:
- `ANNOUNCEMENT_BUTTON_TEXT` : button text on the announcement modal
> feat: add env var to configure announcement modal button text

- src/client/directory/index.tsx
- src/client/user/components/CreateUrlModal/CreateLinkForm.tsx
- src/server/modules/user/UserController.ts
User Story 1 of [Link Transfer Feature](https://github.com/opengovsg/GoGovSG/pull/2179#:~:text=transfer%20feature%20(see-,Notion%20doc,-))
This PR changes the following:
1. Changed `CreateLinkForm` component's error message for short URLs to redirect to `/#/directory?query=${shortUrl}` to query the short URL that already exists
2. Updated error message if short link already exists
**Note:**
With the change, the address bar will not reflect the query as the `useEffect` hook in `SearchPage` component for Directory (which handles the keyword/email search) would set the query to empty as the logic is run once upon initialisation - to be worked on a separate refactoring effort.
- When user attempts to create a short link that already exists, and clicks on the error message, …
> chore: redirect user to existing link in directory

- src/server/modules/threat/FileCheckController.ts
- src/server/modules/threat/__tests__/FileCheckController.test.ts
- src/server/modules/threat/interfaces/FileTypeFilterService.ts
- src/server/modules/threat/interfaces/VirusScanService.ts
- src/server/modules/threat/services/CloudmersiveScanService.ts
- src/server/modules/threat/services/FileTypeFilterService.ts
- src/server/modules/threat/services/__tests__/CloudmersiveScanService.test.ts
We want to allow users to upload zip files, but block users from uploading password-protected files (zip, pdf or otherwise) as Cloudmersive cannot properly scan them for viruses.
1. Allow zip files to be uploaded
2. Switch from using basic file scanning to advanced file scanning on Cloudmersive. This gives us additional options to tell if the file is password protected or not, and block it from being uploaded if it is.
On staging, we should test the following:
Should also update the tests on the release checklist to include password-protected zip/pdf files, if applicable?
Unfortunately, this change doesn't do anything to address the already existing password-protected pdf files on Go, which have not been properly scanned for viruses :(
> feat: allow zip files and block password-protected files

- Dockerfile
- Dockerfile.dev
Closes [Snyk issues](https://app.snyk.io/org/gogovsg/project/a466db86-e13b-4dd1-8b90-2eae048e51da)
Upgraded the Dockerfile's node 16 alpine version from 3.16 to 3.18.
Unfortunately, the upgrade broke the font installation steps later on in the Dockerfile. Investigating this further, I found that in alpine 3.18, running `apk add ttf-freefont` actually installs the package `font-freefont` (`font-freefont-20120503-r4`), instead of `ttf-freefont` (`ttf-freefont-20120503-r2`) in alpine 3.16. Hence the resulting directory for fonts is no longer `/usr/share/fonts/TTF` (containing `.ttf` files), but `/usr/share/fonts/freefont` (containing `.otf` files). This PR fixes the font installation by downloading the `.otf` file into the `freefont` directory.
I couldn't find any documentation for this …
> build: bump alpine to 3.18 in Dockerfile

- package-lock.json
- package.json
Resolves some Snyk high-severity vulnerabilities
Part of Snyk [issue #1](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-PROTOBUFJS-5756498) and [issue #2](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-SEMVER-3247795)
Bump `dd-trace` from `^2.11.0` to `^2.30.1`
> build(deps): bump dd-trace from 2.11.0 to 2.30.1

- src/client/login/actions/index.ts
Possible ReDoS vulnerability on the frontend from glob email validations. Very low severity as it does not affect the backend
Closes [Snyk issue](https://app.snyk.io/org/gogovsg/project/195ed33d-81b4-40d4-9918-45609ce999fb#issue-dce6fcc9-c1da-41db-a4a4-fd17f05ec812)
Ensure that the email is validated to be an actual email, before passing it into the glob expression matcher.
> fix: validate email before passing through glob expression

- package-lock.json
- package.json
Go is currently using `@sentry/cli` v1.67.2 that has a dependency on `ansi-regex` v2.1.1, which has a ReDoS vulnerability
Closes [Snyk issue](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-ANSIREGEX-1583908)
Upgrade `@sentry/cli` v1.67.2 to v1.75.2, which removes its use of `ansi-regex` v2.1.1
We use the `overrides` field in `package.json` to upgrade the `@sentry/cli` version -- see [StackOverflow answer](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) for more details on `overrides`
> build(deps): bump @sentry/cli from 1.67.2 to 1.75.2

- package-lock.json
- package.json
Part of [Snyk issue](https://app.snyk.io/org/gogovsg/project/3fa5b914-3f0f-4828-a3ae-5e77446f64c5#issue-SNYK-JS-D3COLOR-1076592)
Replaces https://github.com/opengovsg/GoGovSG/pull/2229
Bump `react-vis` from 1.11.7 to 1.11.8
> build(deps): bump react-vis from 1.11.7 to 1.11.8
