opengovsg/GoGovSG

src/client/components/HomePage.jsx

Fixes the issue of a missing whitespace in the home page by adding back the accidentally removed whitespace in PR #33.

Added back missing white space

---

.travis.yml
README.md
package-lock.json
package.json
src/client/components/HomePage.jsx
src/client/components/Root.jsx
webpack.config.js

Release 1.13.4 - Send Sentry source-maps on travis build step

---

.github/ISSUE_TEMPLATE/technical_spec.md

Writing a technical spec increases the chances of having a successful project, service, or feature that all stakeholders involved are satisfied with. Not having it decreases the chances of something going horribly wrong during implementation and even after the product is launched.
Adapt the technical specification layout from [Stack Overflow](https://stackoverflow.blog/2020/04/06/a-practical-guide-to-writing-technical-specs/).

Introduce template for technical specs

---

src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/PaginationActionComponent/index.jsx
src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/index.jsx
src/client/components/UserPage/UserLinkTable/UrlTable/MemoTablePagination/styles.ts

- Removed the use of negative margins to center the table footer.
- This solution makes use of `absolute` positioning.

Improved stylings for table footer

---

src/client/components/UserPage/UserLinkTable/ToolBar/FilterSortPanel/index.jsx

Filter reset does not apply until the second attempt
Pass reset'd parameters into the update function

Fix filter

---

package-lock.json
package.json

Use `npm audit fix` to pick up the abovementioned deps, which
contain security fixes

build(deps): update yargs-parser, http-proxy

---

src/server/api/statistics.ts
src/server/constants.ts
src/server/controllers/StatisticsController.ts
src/server/controllers/interfaces/StatisticsControllerInterface.ts
src/server/inversify.config.ts
src/server/repositories/StatisticsRepository.ts
src/server/repositories/UrlRepository.ts
src/server/repositories/UserRepository.ts
src/server/repositories/interfaces/StatisticsRepositoryInterface.ts
src/server/repositories/interfaces/UrlRepositoryInterface.ts
src/server/repositories/interfaces/UserRepositoryInterface.ts
src/server/repositories/types.ts
src/server/services/StatisticsService.ts
src/server/services/interfaces/StatisticsServiceInterface.ts
test/server/mocks/repositories/StatisticsRepository.ts
test/server/services/StatisticsService.test.ts

According to #156, the back-end directory structure beginning to look incoherent and is showing signs of unbridled growth. It is currently a good time for refactoring given the recent expansion of file upload feature.
This PR continues the process of addressing this by refactoring StatisticsController and its dependencies to conform to the Controller Service Repository pattern
- Refactor StatisticsController/Service/Repository
- Statistics makes use of its own repository as statistics for analytics might come from other tables in the future.

Refactor StatisticsController and its dependencies

---

src/server/controllers/LogoutController.ts

LogoutController was missing the injectable annotation
Add injectable annotation

fix: injectable annotation for logout

---

package-lock.json
package.json
src/client/actions/login/index.ts
src/client/actions/login/types.ts
src/client/components/LoginPage/index.jsx
src/client/components/UserPage/Drawer/ControlPanel/index.tsx
src/client/components/UserPage/Drawer/ControlPanel/util/shortlink.ts
src/client/reducers/login/index.ts
src/client/reducers/login/types.ts

Bugfixes
* Frontend login email validation

Release 1.22.2 - Login UI email validation

---

package-lock.json
package.json
src/client/actions/login/index.ts
src/client/actions/login/types.ts
src/client/components/LoginPage/index.jsx
src/client/components/UserPage/Drawer/ControlPanel/index.tsx
src/client/components/UserPage/Drawer/ControlPanel/util/shortlink.ts
src/client/reducers/login/index.ts
src/client/reducers/login/types.ts

Bugfixes
* Frontend now validates for a fully-formed email on the login page

[master] Release 1.22.2

---

package-lock.json
package.json

[develop] Release 1.22.2

---

src/client/components/BaseLayout/BaseLayoutHeader.jsx

Search button on the header is currently not very useful as the integrated home page should already lead to the search page
Remove GoSearch from header

feat: remove search button from header

---

src/client/components/HomePage/index.jsx

The auto redirect from the home page to the user page when the user is logged in is currently disabled for testing when it should not be the case.
Re-enable auto redirect

fix: home page redirect

---

package-lock.json
package.json

To resolve findings from `npm audit`, update commitizen and commitlint dependencies

build(deps): update commitizen, commitlint, others

---

src/client/components/SearchPage/SearchHeader/index.tsx
src/client/components/UserPage/Drawer/ControlPanel/index.tsx
src/client/components/widgets/BetaTag/index.tsx

Search are new beta features but users might not be aware of it.
- Add beta tag to search 
- A distinct preview button instead of save & preview
[Beta tag](https://user-images.githubusercontent.com/35889982/88633106-23828300-d0e7-11ea-90f1-2da1cfdf1b87.png)
[Preview](https://user-images.githubusercontent.com/35889982/88633135-2bdabe00-d0e7-11ea-9ba0-9406427c5088.png)

feat: beta tag and preview

---

src/client/components/widgets/BetaTag/index.tsx

Beta tag has to be resized
Resize beta tag

feat: resize beta tag

---

src/server/repositories/interfaces/OtpRepositoryInterface.ts
src/server/services/interfaces/AuthServiceInterface.ts
src/server/services/interfaces/RedirectServiceInterface.ts
src/server/services/interfaces/StatisticsServiceInterface.ts
src/server/services/interfaces/UrlManagermentServiceInterface.ts

Some services were not documented
Add documentation

docs: add documentation for some services

---

src/server/controllers/UrlCheckController.ts

- If a user has submitted a malicious link, log his/her user id and the url in question
- Log any server errors caught by UrlCheckController

chore(links): log user attempts to create malicious links

---

src/server/controllers/FileCheckController.ts

A pro-active approach is needed to ensure that no malicious content is being publicised by GoGovSG. Ensure that malicious file upload attempts are logged

chore(upload): log user attempts to upload malicious files

---

src/server/views/redirect.ejs
src/server/views/transition-page.ejs

Closes #395 
**Features**:
Transition page auto-redirect countdown is now set to 6 seconds

feat(transition-page): reduce countdown to 6 seconds

---

src/client/components/UserPage/CreateUrlModal/CreateLinkForm.jsx
src/client/components/UserPage/CreateUrlModal/index.jsx
src/client/components/UserPage/index.jsx

Some tech debt was incurred during development/refactors while building recent features. One of which is the deep levels of props drilling which can be solved using redux

Remove props drilling tech debt in url-creation components

---

test/server/api/util.ts
test/server/controllers/LinkStatisticsController.test.ts
test/server/controllers/StatisticsController.test.ts
test/server/respositories/LinkStatisticsRepository.test.ts
test/server/respositories/StatisticsRepository.test.ts

Closes #87
- fix/add tests for stats controllers
- add test suite for StatisticsRepository

test(stats): add/fix statistics tests

---

test/server/controllers/UserController.test.ts

Add the final piece of coverage for the core for GoGovSG

test(controllers): add coverage for UserController

---

package-lock.json
package.json

[develop] Release 1.32.0

---

src/client/components/UserPage/UserLinkTable/ToolBar/Buttons/CreateLinkButton.jsx
src/client/components/UserPage/UserLinkTable/ToolBar/Buttons/templates/ContainedIconButton.jsx

Closes https://github.com/opengovsg/GoGovSG/issues/651
**BEFORE**:
**AFTER**:

fix: update CreateLinkButton icon button to be circle

---

package-lock.json
package.json

Removed webpack-dev-server by mistake, re-adding

build(deps-dev): re-add webpack-dev-server, removed by mistake

---

package-lock.json
package.json
src/client/components/BaseLayout/BaseLayoutHeader.jsx
src/client/components/BaseLayout/Masthead.tsx
src/client/components/BaseLayout/index.jsx
src/client/components/BaseLayout/widgets/Banner.tsx
src/client/components/UserPage/AnnouncementModal/index.tsx

*You may need to clear your cookies before testing this segment.*

Release 1.37.1

---

src/client/home/components/FeatureListSliver.jsx

Closes #948
Refactor the data representation to have a unique `id` key for each column.

fix: refactor data representation to add unique identifier

---

src/server/api/user/index.ts
src/server/controllers/interfaces/FileCheckControllerInterface.ts
src/server/controllers/interfaces/UrlCheckControllerInterface.ts
src/server/inversify.config.ts
src/server/modules/threat/FileCheckController.ts
src/server/modules/threat/UrlCheckController.ts
src/server/modules/threat/__tests__/FileCheckController.test.ts
src/server/modules/threat/__tests__/UrlCheckController.test.ts
src/server/modules/threat/index.ts
src/server/modules/threat/interfaces/FileTypeFilterService.ts
src/server/modules/threat/interfaces/SafeBrowsingRepository.ts
src/server/modules/threat/interfaces/UrlThreatScanService.ts
src/server/modules/threat/interfaces/VirusScanService.ts
src/server/modules/threat/interfaces/index.ts
src/server/modules/threat/mappers/SafeBrowsingMapper.ts
src/server/modules/threat/mappers/index.ts
src/server/modules/threat/repositories/SafeBrowsingRepository.ts
src/server/modules/threat/repositories/__tests__/SafeBrowsingRepository.test.ts
src/server/modules/threat/repositories/index.ts
src/server/modules/threat/services/CloudmersiveScanService.ts
src/server/modules/threat/services/FileTypeFilterService.ts
src/server/modules/threat/services/SafeBrowsingService.ts
src/server/modules/threat/services/__tests__/CloudmersiveScanService.test.ts
src/server/modules/threat/services/__tests__/FileTypeFilterService.test.ts
src/server/modules/threat/services/__tests__/SafeBrowsingService.test.ts
src/server/modules/threat/services/index.ts
src/server/services/interfaces/UrlThreatScanServiceInterface.ts
test/server/api/util.ts

Move everything related to file and URL checking into `module/threat`,
including tests, mappers and repositories
Ongoing work for #869

refactor(threat): make module, move file and url checks

---

src/client/directory/components/DirectoryHeader/DirectoryInput/FilterDrawer/index.tsx
src/client/directory/components/DirectoryHeader/DirectoryInput/SortDrawer/index.tsx
src/client/directory/components/DirectoryHeader/DirectoryInput/index.tsx
src/client/directory/components/DirectoryHeader/index.tsx
src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTablePagination/index.tsx
src/client/directory/components/DirectoryResults/DirectoryTable/DirectoryTableRow/index.tsx
src/client/directory/components/DirectoryResults/DirectoryTable/index.tsx
src/client/directory/components/DirectoryResults/MobilePanel/index.tsx
src/client/directory/components/DirectoryResults/index.tsx
src/client/directory/components/EmptySearchGraphic/index.tsx
src/client/directory/constants.ts
src/client/directory/index.tsx
src/server/repositories/UrlRepository.ts
src/server/services/interfaces/DirectorySearchServiceInterface.ts

Documenting GoDirectory's code for next developer
Closes #1076 
- Add docs for components and functions in client
- Add docs for private functions in server

JSdoc directory

---

.gitpod.Dockerfile
.gitpod.yml

Resolve the problem with gitpod once and for all

fix(gitpod): install localstack via gitpod, not dockerfile

---

public/assets/not-found-page/styles/not-found-page.css
public/assets/shared/colours.css
public/assets/shared/shared-styles.css
public/assets/transition-page/styles/transition-page.css
src/server/config.ts
src/server/index.ts
src/server/views/404.error.ejs
src/server/views/transition-page.ejs

Not all styles were copied over from govtech-sgds to the transition page
copy missing sgds styles

fix(tp): copy missing sgds styles

---

src/server/modules/user/__tests__/UserController.test.ts

covers the error handling for `NotFoundError`, `AlreadyExistsError` and `Sequelize.ValidationError` functions in `UserController.createUrl`

test(user-controller): added tests to cover create-url function error handling

---

.github/mergify.yml

Correct the regex used to identify dependabot PRs for merging

fix(mergify): correct dependabot title regex

---

package-lock.json

`handlebars` package susceptible to RCE when compiling templates.
https://npmjs.com/advisories/1670
Patch via `npm audit fix`.

fix: npm audit fix for handlebars

---

src/server/views/transition-page.ejs

Correct the typo in the path for the background image in the transition page

fix(tp): correct typo for background-image path

---

package-lock.json
package.json

Remove @types/bluebird, given that we do not use Bluebird in the codebase

build(deps): remove @types/bluebird, not used

---

package-lock.json
package.json

Verified that there are no breaking changes on staging

build(deps): Upgrade aws-sdk from 2.977.0 to 2.1102.0

---

test/end-to-end/UserPage.test.ts
test/end-to-end/util/LoginProcedure.ts

Should've gotten rid of some stray comments and things from #1983, sorry about that!

chore: clean up e2e tests

---

src/client/user/actions/index.ts
test/end-to-end/util/helpers.ts

Adds action to trigger status bar In progress display after bulk creation has completed

chore: display QR code inprogress after bulk upload

---

src/server/serverless/lambda-migrate-url-to-user/index.js
src/server/serverless/lambda-migrate-user-links/index.js

- Inaccurate status for AWS lambda migrate url to user
- Inaccurate status for AWS lambda migrate user links
Closes [#2045 ](https://github.com/opengovsg/GoGovSG/issues/2045)

chore: return error result in migrate-user-links and migrate-url-to-user lambdas

---

src/server/services/email.ts

chore: fix copy

---

src/server/services/email.ts

chore: fix email copy

---

public/locales/edu/en/translation.json
public/locales/health/en/translation.json
src/client/app/components/BaseLayout/BaseLayoutHeader.tsx

Changes:
- fix broken links for health
- add links to edu
More copy changes:
- Rename "Guide" to "FAQ"
- Standardize on "Send us feedback" instead of "Help us improve"

chore: fix links for health and edu
